# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-computations
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: computations
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: computations
    spec:
      containers:
        - env:
            - name: MF_THINGS_DB
              value: {{ .Values.postgresqlthings.auth.database | quote }}
            - name: MF_THINGS_DB_HOST
            {{- if .Values.postgresqlthings.enabled }}
              value: {{ .Release.Name }}-postgresqlthings
            {{- else }}
              value: {{ .Values.postgresqlthings.postgresqlHost | quote}}
            {{- end }}
            - name: MF_THINGS_DB_PASS
              value: {{ .Values.postgresqlthings.auth.password | quote}}
            - name: MF_THINGS_DB_PORT
              value: "{{ .Values.computations.dbPort }}"
            - name: MF_THINGS_DB_USER
              value: {{ .Values.postgresqlthings.auth.username | quote}}
            - name: MF_THINGS_ES_URL
              value: {{ .Release.Name }}-redis-streams-master:{{ .Values.computations.redisESPort }}
            - name: MF_THINGS_HTTP_PORT
              value: "{{ .Values.computations.httpPort }}"
            - name: MF_THINGS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.computations.logLevel }}
            - name: MF_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.users.grpcPort }}
          image: "{{ default .Values.defaults.image.repository .Values.computations.image.repository }}/computations:{{ default .Values.defaults.image.tag .Values.computations.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.computations.image.pullPolicy }}
          name: {{ .Release.Name }}-computations
          ports:
            - containerPort: {{ .Values.computations.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.computations.authGrpcPort }}
              protocol: TCP
            - containerPort: {{ .Values.computations.authHttpPort }}
              protocol: TCP
      {{- with .Values.defaults.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always