defaults:
  logLevel: "info"
  image:
    pullPolicy: "IfNotPresent"
    repository: "prism"
    tag: "latest"
  replicaCount: 1
  jaegerPort: 6831

ingress:
  enabled: true
  annotations:
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: "autha-dev-letsencrypt-prod"
    #nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
  labels: {}
  # Uncomment this block for TLS support in public ingress
  hostname: "testauth.ddns.net"
  tls:
    hostname: "testauth.ddns.net"
    secret: "testauth-ddns-net-secret"

nginxInternal:
  mtls:
    # By default mTLS is disabled. If you use mTLS, comment this block.
    tls: ""
    intermediateCrt: ""
    # Uncomment this block for TLS and mTLS support.
    # Use sh script from /secrets/secrets.sh to create config maps with your certs
    # tls: "prism-server"
    # intermediateCrt: "ca"

computations:
  image: {}
  dbPort: 5432
  httpPort: 9000
  authGrpcPort: 7004

computationsdb:
  image: {}
  enabled: true
  name: computationsdb
  postgresqlHost: localhost
  auth:
    username: "prism"
    password: "prism"
    database: "computations"
  primary:
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
    persistence:
      storageClass: "do-block-storage"
      size: 1Gi
  readReplicas:
    replicaCount: 0

users:
  image: "https://hub.docker.com/u/mainflux/latest"
  dbPort: 5432
  httpPort: 9002
  grpcPort: 7001
  adminEmail: "admin@example.com"
  adminPassword: "12345678"

usersdb:
  image: {}
  start: true
  name: usersdb
  postgresqlHost: localhost
  auth:
    username: "prism"
    password: "prism"
    database: "users"
  primary:
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
    persistence:
      storageClass: "do-block-storage"
      size: 1Gi
  readReplicas:
    replicaCount: 0

ui:
  enabled: false
  image: {}
  port: 3000
  proxyAuth: false
  prefix: "ui"
  logoutUrl: "/logout"

# All options for loki-stack: https://github.com/grafana/helm-charts/tree/main/charts/loki-stack
loki-stack:
  enabled: true
  loki:
    enabled: false
    persistence:
      enabled: true
  promtail:
    enabled: false
  fluent-bit:
    enabled: false
  grafana:
    enabled: true
    sidecar:
      datasources:
        enabled: true
    rbac:
      pspEnabled: false
    image:
      tag: 8.1.6
    # grafana.ini:
    #   server:
    #     domain: testauth.ddns.net
    #     root_url: "%(protocol)s://%(domain)s/grafana"
    #     serve_from_sub_path: true
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "autha-dev-letsencrypt-prod"
        nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
      hosts:
        - "testauth.ddns.net"
      tls:
        - secretName: testauth-ddns-net-secret
          hosts:
            - testauth.ddns.net
      path: "/grafana"
    persistence:
      enabled: false
      size: 1Gi
  prometheus:
    enabled: false
