# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: prism
description: Prism AI
icon: https://avatars1.githubusercontent.com/u/13207490
type: application
version: 1.0.0
appVersion: 1.0.0
sources:
  - https://hub.docker.com/u/magistrala
maintainers:
  - name: dusan
    email: dusan.borovcanin@ultraviolet.rs

dependencies:
  - name: argo-rollouts
    version: "2.39.1"
    repository: "https://argoproj.github.io/argo-helm"
    alias: argoRollouts
    condition: argoRollouts.enabled

  - name: external-secrets
    version: 0.17.1-rc1
    repository: "https://charts.external-secrets.io/"
    alias: externalsecrets
    condition: externalsecrets.enabled

  - name: fluent-bit
    version: "0.49.0"
    repository: "https://fluent.github.io/helm-charts"
    alias: fluentbit
    condition: fluentbit.enabled

  - name: opensearch
    version: "3.0.0"
    repository: "https://opensearch-project.github.io/helm-charts"
    alias: opensearch
    condition: opensearch.enabled

  - name: opensearch-dashboards
    version: "3.0.0"
    repository: "https://opensearch-project.github.io/helm-charts"
    alias: opensearch-dashboards
    condition: opensearch-dashboards.enabled

  - name: metrics-server
    version: 3.12.2
    repository: https://kubernetes-sigs.github.io/metrics-server
    alias: metrics-server

  - name: kube-prometheus-stack
    version: "70.0.2"
    repository: "https://prometheus-community.github.io/helm-charts"
    alias: prometheus
    condition: prometheus.enabled

  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 19.6.2
    alias: redis-clients

  - name: nats
    version: "1.2.1"
    repository: https://nats-io.github.io/k8s/helm/charts/

  - name: jaeger
    version: "3.4.0"
    repository: https://jaegertracing.github.io/helm-charts
    alias: jaeger

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlauth
    condition: postgresqlauth.enabled

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlspicedb
    condition: postgresqlspicedb.enabled

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlusers
    condition: postgresqlusers.enabled

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlcomputations
    condition: postgresqlthings.enabled

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlbackends
    condition: postgresqlbackends.enabled

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlamcerts
    condition: postgresqlamcerts.enabled

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlbilling
    condition: postgresqlbilling.enabled

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqldomains
    condition: postgresqldomains.enabled

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlcvmbilling
    condition: postgresqlcvmbilling.enabled
