# Global configuration
defaults:
  logLevel: "info"
  image:
    pullPolicy: "IfNotPresent"
    repository: "magistrala"
    tag: "latest"
    # pullSecrets: {}
  # Replicas of MQTT adapter, NATS, Things, Envoy and Auth
  replicaCount: 1
  natsPort: 4222
  jaegerCollectorPort: 4318
  jaegerTraceRatio: 10
  sendTelemetry: true
  eventStreamURL: "magistrala-nats:4222"

users:
  image: {}
     # pullSecrets: {}
     # repository: "magistrala/users"
     # tag: "latest"
     # pullPolicy: "IfNotPresent"
  # jaegerTraceRatio: 10
  # sendTelemetry: true
  # logLevel: "info"
  httpPort: 9002
  grpcPort: 7001
  adminEmail: "admin@example.com"
  adminPassword: "12345678"
  secretKey: "supersecretkey"
  passwordRegex: "^.{8,}$"
  tokenResetEndpoint: "^[a-zA-Z0-9!@#$%^&*]{8,}$"
  allowSelfRegister: true
  deleteInterval: "24h"
  deleteAfter: "720h"
  tokenResetEndpoint: "http://example.com/reset"

# Auth service configuration
auth:
  grpcPort: 7001

# Database configuration
postgresqlusers:
  enabled: true
  host: localhost
  port: 5432
  database: users
  username: "prism"
  password: "prism"
