# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-am-certs
spec:
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
        - setWeight: 100
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable: 0%
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: am-certs
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.certs.httpPort }}"
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/am-certs-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        component: am-certs
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.amCerts.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-am-certs
          image: "{{ default (printf "%s/certs" .Values.defaults.image.rootRepository) .Values.amCerts.image.repository }}:{{ default .Values.defaults.image.tag .Values.amCerts.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.amCerts.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-am-certs-env-vars
          env:
            - name: AM_CERTS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prism-am-certs-secrets
                  key: AM_CERTS_DB_PASS
            - name: AM_CERTS_GRPC_CLIENT_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: AM_CERTS_GRPC_CLIENT_CA_CERTS
            - name: AM_CERTS_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: AM_CERTS_GRPC_SERVER_CA_CERTS
            - name: AM_CERTS_GRPC_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: AM_CERTS_GRPC_SERVER_CERT
            - name: AM_CERTS_GRPC_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: AM_CERTS_GRPC_SERVER_KEY
          ports:
            - containerPort: 9010
              protocol: TCP
            - containerPort: 7012
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.amCerts.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.amCerts.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: {{ .Release.Name }}-am-certs-org-config
              mountPath: /config/config.yml
              subPath: config.yml
              readOnly: true
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

      volumes:
        - name: {{ .Release.Name }}-am-certs-org-config
          configMap:
            name: {{ .Release.Name }}-am-certs-org-config-files
