# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-am-certs-env-vars
data:
  AM_JAEGER_URL: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.jaeger.collector.service.otlp.http.port }}/v1/traces"
  PRISM_JAEGER_TRACE_RATIO: {{ default .Values.defaults.jaegerTraceRatio .Values.defaults.jaegerTraceRatio | quote }}
  PRISM_SEND_TELEMETRY: {{ default .Values.defaults.sendTelemetry .Values.defaults.sendTelemetry | quote }}
  PRISM_CERTS_LOG_LEVEL: {{ default .Values.defaults.logLevel .Values.certs.logLevel | quote }}
  AM_CERTS_DB_HOST:
        {{- if .Values.postgresqlamcerts.enabled }}
          "{{ .Release.Name }}-postgresqlamcerts"
        {{- else }}:
          {{ .Values.postgresqlamcerts | quote }}
        {{- end }}
  AM_CERTS_DB_PORT: {{ .Values.postgresqlamcerts.port | quote }}
  AM_CERTS_DB_NAME: {{ .Values.postgresqlamcerts.database | quote }}
  AM_CERTS_DB_USER: {{ .Values.postgresqlamcerts.username | quote }}
  AM_CERTS_DB_SSL_MODE: {{ .Values.amCerts.sslMode | quote }}
  AM_CERTS_GRPC_HOST: "0.0.0.0"
  AM_CERTS_GRPC_PORT: {{ .Values.amCerts.grpcPort | quote }}
  AM_CERTS_HTTP_HOST: "0.0.0.0"
  AM_CERTS_HTTP_PORT: {{ .Values.amCerts.httpPort | quote }}
  AM_CERTS_LOG_LEVEL: {{ .Values.amCerts.logLevel | quote }}
  AM_JAEGER_TRACE_RATIO: {{ default .Values.defaults.jaegerTraceRatio .Values.amCerts.jaegerTraceRatio | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-am-certs-org-config-files
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
data:
  config.yml: |
    common_name: "Ultraviolet_Selfsigned_ca"
    organization:
      - "Ultraviolet"
    organizational_unit:
      - "Ultraviolet_ca"
    country:
      - "France"
    province:
      - "Paris"
    locality:
      - "Quai de Valmy"
    postal_code:
      - "75010 Paris"
    dns_names:
      - "prism.ultraviolet.rs"
      - "109.92.195.153"
      - "staging.prism.ultraviolet.rs"
    ip_addresses:
      - "109.92.195.153"
    extra_data: ""
