# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-am-certs
spec:
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable: 25%
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: am-certs
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.certs.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: am-certs
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.amCerts.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-am-certs
          image: "{{ default (printf "%s/certs" .Values.defaults.image.rootRepository) .Values.amCerts.image.repository }}:{{ default .Values.defaults.image.tag .Values.amCerts.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.amCerts.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-am-certs-env-vars
          ports:
            - containerPort: 9010
              protocol: TCP
            - containerPort: 7012
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.amCerts.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.amCerts.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: {{ .Release.Name }}-am-certs-ssl-config
              mountPath: /ssl/certs/certificates
              readOnly: true
            - name: {{ .Release.Name }}-am-certs-org-config
              mountPath: /config/config.yml
              subPath: config.yml
              readOnly: true
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

      volumes:
        - name: {{ .Release.Name }}-am-certs-ssl-config
          configMap:
            name: {{ .Release.Name }}-am-certs-ssl-files
        - name: {{ .Release.Name }}-am-certs-org-config
          configMap:
            name: {{ .Release.Name }}-am-certs-org-config-files-v1.0.1
