apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backends-secrets
  namespace: {{ .Release.Namespace }}
data:
  server-cert.pem: |
  server-key.pem: |
  ca-cert.pem: |
  ca-key.pem: |
  client-cert.pem: |
  client-key.pem: |
  ARM_SUBSCRIPTION_ID: ""
  ARM_CLIENT_ID: ""
  ARM_CLIENT_SECRET: ""
  ARM_TENANT_ID: ""
stringData:
  google_application_credentials.json: |
    {}
