# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:  
  name: {{ .Release.Name }}-backends
spec:
  type: ClusterIP
  selector:    
    app: {{ .Release.Name }}    
    component: backends  
  ports:    
    - port: {{ .Values.backends.httpPort }}      
      protocol: TCP
      targetPort: {{ .Values.backends.httpPort}}
      name: {{ .Release.Name }}-backends-{{ .Values.backends.httpPort }}    
    - port: {{ .Values.backends.grpcPort }}
      protocol: TCP
      targetPort: {{ .Values.backends.grpcPort }}
      name: {{ .Release.Name }}-backends-{{ .Values.backends.grpcPort }}
    - port: {{ .Values.backends.cvmsPort }}
      protocol: TCP
      targetPort: {{ .Values.backends.cvmsPort }}
      name: {{ .Release.Name }}-backends-{{ .Values.backends.cvmsPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backends-headless
spec:
  selector:
    app: {{ .Release.Name }}
    component: backends
  ports:
    - port: {{ .Values.backends.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-backends-{{ .Values.backends.httpPort }}
    - port: 7001
      protocol: TCP
      name: {{ .Release.Name }}-backends-7001
    - port: {{ .Values.backends.grpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-backends-{{ .Values.backends.grpcPort }}
  clusterIP: None
