# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-backends
spec:
  replicas: 1
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable: 25%
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: backends
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.backends.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: backends
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.ui.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-backends
          image: "{{ default (printf "%s/backends" .Values.defaults.image.rootRepository) .Values.backends.image.repository }}:{{ default .Values.defaults.image.tag .Values.backends.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.backends.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backends-env-vars
          ports:
            - containerPort: {{ .Values.backends.httpPort }}
              protocol: TCP
            - containerPort: 7006
              protocol: TCP
            - containerPort: 7011
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-backends-ssl-config
              mountPath: /ssl/certs/backends
              readOnly: true
            - name: {{ .Release.Name }}-backends-providers-config
              mountPath: /providers
              readOnly: true
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "350m"
              memory: "512Mi"

      volumes:
        - name: {{ .Release.Name }}-backends-ssl-config
          configMap:
            name: {{ .Release.Name }}-backends-ssl-files

        - name: {{ .Release.Name }}-backends-providers-config
          configMap:
            name: {{ .Release.Name }}-backends-providers-config-files
