# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backends
spec:
  selector:
    app: {{ .Release.Name }}
    component: backends
  ports:
    - port: {{ .Values.backends.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-backends-{{ .Values.backends.httpPort }}
    - port: {{ .Values.backends.authGrpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-backends-{{ .Values.backends.authGrpcPort }}
    - port: {{ .Values.backends.authHttpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-backends-{{ .Values.backends.authHttpPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backends-headless
spec:
  selector:
    app: {{ .Release.Name }}
    component: backends
  ports:
    - port: {{ .Values.backends.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-backends-{{ .Values.backends.httpPort }}
    - port: {{ .Values.backends.authGrpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-backends-{{ .Values.backends.authGrpcPort }}
    - port: {{ .Values.backends.authHttpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-backends-{{ .Values.backends.authHttpPort }}
  clusterIP: None
