# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backends-env-vars
  namespace: {{ .Release.Namespace }}
data:
  PRISM_JAEGER_URL: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.defaults.jaegerCollectorPort }}/v1/traces"
  PRISM_BACKENDS_AUTH_GRPC_HOST: "{{ .Release.Name }}-{{ .Values.auth.host }}"
  PRISM_BACKENDS_DB_HOST:
    {{- if .Values.postgresqlbackends.enabled }}
      "{{ .Release.Name }}-postgresqlbackends"
    {{- else }}
      {{ .Values.postgresqlbackends.host | quote }}
    {{- end }}
  PRISM_BACKENDS_DB_PORT: {{ .Values.postgresqlbackends.port | quote }}
  PRISM_BACKENDS_DB_USER: {{ .Values.postgresqlbackends.username | quote }}
  PRISM_BACKENDS_DB: {{ .Values.postgresqlbackends.database | quote }}
  PRISM_ES_STORE_URL: "{{ .Release.Name}}-{{ .Values.defaults.eventStreamURL }}"
  PRISM_BACKENDS_HTTP_HOST: "0.0.0.0"
  PRISM_BACKENDS_HTTP_PORT: {{ .Values.backends.httpPort | quote }}
  PRISM_BACKENDS_LOG_LEVEL: {{ default .Values.defaults.logLevel .Values.backends.logLevel | quote }}
  PRISM_BACKENDS_GRPC_HOST: "0.0.0.0"
  PRISM_BACKENDS_GRPC_PORT: {{ .Values.backends.grpcPort | quote }}
  PRISM_AUTH_GRPC_URL: "{{ .Release.Name }}-{{ .Values.auth.host }}:{{ .Values.auth.grpcPort }}"
  PRISM_BACKENDS_DB_SSL_CERT: ""
  PRISM_BACKENDS_DB_SSL_KEY: ""
  PRISM_BACKENDS_DB_SSL_MODE: "disable"
  PRISM_BACKENDS_DB_SSL_ROOT_CERT: ""
  PRISM_BACKENDS_INSTANCE_ID: ""
  PRISM_CERTS_GRPC_CLIENT_TLS: "true"
  PRISM_CERTS_GRPC_TIMEOUT: ""
  PRISM_CERTS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.amCerts.host}}:{{ .Values.amCerts.grpcPort }}"
  PRISM_CERTS_HOST: "{{ .Release.Name }}-{{ .Values.amCerts.host }}"
  PRISM_CERTS_TLS_VERIFICATION: "false"
  PRISM_CERTS_URL: "{{ if .Values.env.prod }}https{{ else }}http{{ end }}://{{ .Release.Name }}-{{ .Values.amCerts.host }}:{{ .Values.amCerts.httpPort }}"
  PRISM_SPICEDB_HOST: "{{ .Release.Name }}-{{ .Values.spicedb.host }}"
  PRISM_SPICEDB_PORT: {{ .Values.spicedb.grpc.port | quote }}
  PRISM_UI_CERTS_URL: "{{ if .Values.env.prod }}https{{ else }}http{{ end }}://{{ .Release.Name }}-{{ .Values.certs.host }}:{{ .Values.certs.httpPort }}"
  PRISM_USERS_GRPC_CLIENT_TLS: "false"
  PRISM_USERS_GRPC_TIMEOUT: "10s"
  PRISM_USERS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.users.host }}:{{ .Values.users.grpcPort }}"
  PRISM_DOMAINS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.domains.host }}:{{ .Values.domains.grpcPort }}"
  PRISM_DOMAINS_GRPC_TIMEOUT: "10s"
  PRISM_CVMS_PUBLIC_URL: "{{ .Values.env.prod | ternary "prism.ultraviolet.rs" "staging.prism.ultraviolet.rs" }}:{{ .Values.backends.cvmsPort }}"
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/secret/google_application_credentials.json"
  PRISM_MANAGER_GRPC_HOST: "{{ .Values.backends.managerGrpcHost }}"
  PRISM_MANAGER_GRPC_PORT: {{ .Values.backends.managerGrpcPort | quote }}
  PRISM_MANAGER_GRPC_URL: "{{ .Values.backends.managerGrpcHost }}:{{ .Values.backends.managerGrpcPort }}"
  PRISM_CVM_GRPC_HOST: "0.0.0.0"
  PRISM_CVM_GRPC_PORT: "{{ .Values.backends.cvmsPort }}"
  PRISM_CVM_GRPC_SERVER_CERT: "/etc/certs/prism-server.crt"
  PRISM_CVM_GRPC_SERVER_KEY: "/etc/certs/prism-server.key"
  PRISM_CVM_GRPC_SERVER_CA_CERTS: "/etc/certs/ca.crt"
  PRISM_CVM_GRPC_CLIENT_CA_CERTS: "/etc/certs/ca.crt"
  PRISM_CVM_GRPC_SERVER_CA_KEY: "/etc/certs/ca.key"
  CERTS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.certs.host }}:{{ .Values.certs.grpcPort }}"
  CERTS_GRPC_TIMEOUT: "10s"
  CERTS_GRPC_CLIENT_TLS: ""
  CERTS_GRPC_SERVER_CA_CERTS: ""
  SECRET_NAME: "prism-backends-secrets"
  SECRET_NAMESPACE: "{{ .Release.Namespace }}"
  PRISM_BILLING_URL: "{{ if .Values.env.prod }}https{{ else }}http{{ end }}://{{ .Release.Name }}-{{ .Values.billing.host }}:{{ .Values.billing.httpPort }}"
  PRISM_AM_CERTS_PUBLIC_URL: "{{ .Values.env.prod | ternary "prism.ultraviolet.rs/am-certs" "staging.prism.ultraviolet.rs/am-certs" }}"
  PRISM_CALLOUT_URLS: "{{ if .Values.env.prod }}https{{ else }}http{{ end }}://{{ .Release.Name }}-{{ .Values.billing.host }}:{{ .Values.billing.httpPort }}/auth"
  PRISM_CALLOUT_METHOD: "{{ .Values.callouts.method }}"
  PRISM_CALLOUT_TLS_VERIFICATION: "false"
  PRISM_CALLOUT_TIMEOUT: "10s"
  PRISM_CALLOUT_OPERATIONS: "{{ .Values.callouts.operations.prism }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backends-providers-config-files
data:
  azure.toml: |-
{{ include "providers.azure.toml" . | indent 4 }}
  manager.toml: |-
{{ include "providers.manager.toml" . | indent 4 }}
  gcp.toml: |-
{{ include "providers.gcp.toml" . | indent 4 }}
  gcp_main.tf: |-
{{ include "providers.gcp.main.tf" . | indent 4 }}
  gcp_kms_main.tf: |-
{{ include "providers.gcp.kms.main.tf" . | indent 4 }}
  azure_main.tf: |-
{{ include "providers.azure.main.tf" . | indent 4 }}
  azure_kms_main.tf: |-
{{ include "providers.azure.kms.main.tf" . | indent 4 }}
  cloud_init.yml: |-
{{ include "providers.cloud.init.yml" . | indent 4 }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backends-cvms-cert-init-script
  namespace: {{ .Release.Namespace }}
data:
  provision_certs.sh: |
{{ .Files.Get "scripts/provision_certs.sh" | indent 4 }}
