# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-billing
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
    component: billing
  ports:
    - protocol: TCP
      port: {{ .Values.billing.httpPort }}
      name: {{ .Release.Name }}-billing-http
