# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-billing
spec:
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable: 25%
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: billing
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.billing.httpPort }}"
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/billing-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        component: billing
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.billing.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-billing
          image: "{{ default (printf "%s/billing" .Values.defaults.image.rootRepository) .Values.billing.image.repository }}:{{ default .Values.defaults.image.tag .Values.billing.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.billing.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-billing-env-vars
          env:
            - name: MG_BILLING_STRIPE_PK
              valueFrom:
                secretKeyRef:
                  name: prism-billing-secrets
                  key: MG_BILLING_STRIPE_PK
            - name: MG_BILLING_STRIPE_WEBHOOKSECRET
              valueFrom:
                secretKeyRef:
                  name: prism-billing-secrets
                  key: MG_BILLING_STRIPE_WEBHOOKSECRET
            - name: MG_BILLING_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prism-billing-secrets
                  key: MG_BILLING_DB_PASS
            - name: MG_BILLING_GRPC_CLIENT_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: MG_BILLING_GRPC_CLIENT_CA_CERTS
            - name: MG_BILLING_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: MG_BILLING_GRPC_SERVER_CA_CERTS
            - name: MG_BILLING_GRPC_SERVER_CA_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: MG_BILLING_GRPC_SERVER_CA_KEY
            - name: MG_BILLING_GRPC_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: MG_BILLING_GRPC_SERVER_CERT
            - name: MG_BILLING_GRPC_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: MG_BILLING_GRPC_SERVER_KEY
            - name: SMQ_AUTH_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_CERT
            - name: SMQ_AUTH_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_KEY
            - name: SMQ_AUTH_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_AUTH_GRPC_SERVER_CA_CERTS
            - name: MG_DOMAINS_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_CERT
            - name: MG_DOMAINS_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_KEY
            - name: MG_DOMAINS_GRPC_CLIENT_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS
          ports:
            - containerPort: {{ .Values.billing.httpPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.billing.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.billing.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
