# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- define "billing.default.plan.toml" -}}

name = 'Free Tier'
amount = 0
currency = 'EUR'
description = 'Free plan'

[limits]
[limits.computation]
create = 10
run = 5

[limits.cvm]
create = 5

[limits.workspace]
membership = 3

[metadata]
Providers = ["manager", "external"]
Description = "Short Lived CVMs (TTL 10m)"

{{- end -}}
