# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-certs
spec:
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
        - setWeight: 100
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable: 0%
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: certs
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.certs.httpPort }}"
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/certs-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        component: certs
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.certs.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-certs
          image: "{{ default (printf "%s/certs" .Values.defaults.image.rootRepository) .Values.certs.image.repository }}:{{ default .Values.defaults.image.tag .Values.certs.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.certs.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-certs-env-vars
          env:
            - name: PRISM_SPICEDB_PRE_SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-spicedb-secrets
                  key: PRISM_SPICEDB_PRE_SHARED_KEY
            - name: PRISM_AUTH_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_CERT
            - name: PRISM_AUTH_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_KEY
            - name: PRISM_AUTH_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_AUTH_GRPC_SERVER_CA_CERTS
            - name: PRISM_CERTS_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_CERTS_GRPC_CLIENT_CERT
            - name: PRISM_CERTS_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_CERTS_GRPC_CLIENT_KEY
            - name: PRISM_CERTS_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_CERTS_GRPC_SERVER_CA_CERTS
            - name: PRISM_CERTS_HTTP_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_CERTS_HTTP_SERVER_CERT
            - name: PRISM_CERTS_HTTP_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_CERTS_HTTP_SERVER_KEY
            - name: PRISM_USERS_GRPC_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_USERS_GRPC_CLIENT_CA_CERTS
            - name: CERTS_GRPC_CLIENT_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: AM_CERTS_GRPC_CLIENT_CA_CERTS
            - name: CERTS_GRPC_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: AM_CERTS_GRPC_SERVER_CERT
            - name: CERTS_GRPC_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: AM_CERTS_GRPC_SERVER_KEY
            - name: CERTS_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: AM_CERTS_GRPC_SERVER_CA_CERTS
            - name: PRISM_DOMAINS_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_CERT
            - name: PRISM_DOMAINS_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_KEY
            - name: PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS
          ports:
            - containerPort: {{ .Values.certs.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.certs.grpcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.certs.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.certs.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
