# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.certs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-certs
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: certs
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.certs.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: certs
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.certs.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-certs
          image: "{{ default (printf "%s/certs" .Values.defaults.image.rootRepository) .Values.certs.image.repository }}:{{ default .Values.defaults.image.tag .Values.certs.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.certs.image.pullPolicy }}
          env:
            - name: PRISM_JAEGER_URL
              value: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.jaeger.collector.service.otlp.http.port }}/v1/traces"
            - name: PRISM_JAEGER_TRACE_RATIO
              value: {{ default .Values.defaults.jaegerTraceRatio .Values.certs.jaegerTraceRatio | quote }}
            - name: PRISM_SEND_TELEMETRY
              value: {{ default .Values.defaults.sendTelemetry .Values.certs.sendTelemetry | quote }}
            - name: PRISM_CERTS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.certs.logLevel | quote }}
            - name: PRISM_CERTS_HTTP_HOST
              value: "0.0.0.0"
            - name: PRISM_CERTS_HTTP_PORT
              value: {{ .Values.certs.httpPort | quote }}
            - name: PRISM_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.auth.grpcPort }}
            - name: PRISM_CERTS_DB_HOST
            {{- if .Values.postgresqlcerts.enabled }}
              value: {{ .Release.Name }}-postgresqlcerts
            {{- else }}
              value: {{ .Values.postgresqlcerts.host | quote }}
            {{- end }}
            - name: PRISM_CERTS_DB_PORT
              value: {{ .Values.postgresqlcerts.port | quote }}
            - name: PRISM_CERTS_DB_NAME
              value: {{ .Values.postgresqlcerts.database | quote }}
            - name: PRISM_CERTS_DB_USER
              value: {{ .Values.postgresqlcerts.username | quote }}
            - name: PRISM_CERTS_DB_PASS
              value: {{ .Values.postgresqlcerts.password | quote }}
            - name: PRISM_CERTS_SIGN_CA_PATH
              value: {{ .Values.certs.signCAPath }}
            - name: PRISM_CERTS_SIGN_CA_KEY_PATH
              value: {{ .Values.certs.signCAKeyPath }}
            - name: PRISM_CERTS_VAULT_HOST
              value: {{ .Values.certs.vault.url | quote }}
            - name:  PRISM_CERTS_VAULT_APPROLE_ROLEID
              value: {{ .Values.certs.vault.approleRoleid | quote }}
            - name: PRISM_CERTS_VAULT_APPROLE_SECRET
              value: {{ .Values.certs.vault.approleSecret | quote }}
            - name: PRISM_CERTS_VAULT_NAMESPACE
              value: {{ .Values.certs.vault.namespace | quote }}
          ports:
            - containerPort: {{ .Values.certs.httpPort }}
              protocol: TCP
{{- end }}