# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-computations
spec:
  selector:
    app: {{ .Release.Name }}
    component: computations
  ports:
    - port: {{ .Values.computations.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-computations-{{ .Values.computations.httpPort }}
    - port: {{ .Values.computations.authGrpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-computations-{{ .Values.computations.authGrpcPort }}
    - port: {{ .Values.computations.authHttpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-computations-{{ .Values.computations.authHttpPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-computations-headless
spec:
  selector:
    app: {{ .Release.Name }}
    component: computations
  ports:
    - port: {{ .Values.computations.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-computations-{{ .Values.computations.httpPort }}
    - port: {{ .Values.computations.authGrpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-computations-{{ .Values.computations.authGrpcPort }}
    - port: {{ .Values.computations.authHttpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-computations-{{ .Values.computations.authHttpPort }}
  clusterIP: None
