# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-computations
spec:
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable:
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: computations
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.computations.httpPort }}"
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/computations-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        component: computations
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.ui.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-computations
          image: "{{ default (printf "%s/computations" .Values.defaults.image.rootRepository) .Values.computations.image.repository }}:{{ default .Values.defaults.image.tag .Values.computations.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.computations.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-computations-env-vars
          env:
            - name: PRISM_COMPUTATIONS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-computations-secrets
                  key: PRISM_COMPUTATIONS_DB_USER
            - name: PRISM_COMPUTATIONS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-computations-secrets
                  key: PRISM_COMPUTATIONS_DB_PASS
            - name: PRISM_COMPUTATIONS_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-computations-secrets
                  key: PRISM_COMPUTATIONS_DB_NAME
            - name: PRISM_SPICEDB_PRE_SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-spicedb-secrets
                  key: PRISM_SPICEDB_PRE_SHARED_KEY
          ports:
            - containerPort: {{ .Values.computations.httpPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.computations.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.computations.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /spicedb
              name: spicedb-schema-zed
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: spicedb-schema-zed
          configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-spicedb-schema-zed
            optional: false
