# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-computations-env-vars
data:
  PRISM_JAEGER_URL: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.defaults.jaegerCollectorPort }}/v1/traces"
  PRISM_COMPUTATIONS_AUTH_GRPC_HOST: "{{ .Release.Name }}-{{ .Values.auth.host }}"
  PRISM_COMPUTATIONS_AUTH_GRPC_PORT: {{ .Values.auth.grpcPort | quote }}
  PRISM_COMPUTATIONS_DB_HOST:
    {{- if .Values.postgresqlcomputations.enabled }}
        "{{ .Release.Name }}-postgresqlcomputations"
    {{- else }}
      {{ .Values.postgresqlcomputations.host | quote }}
    {{- end }}
  PRISM_COMPUTATIONS_DB_PORT: {{ .Values.postgresqlcomputations.port | quote }}
  PRISM_COMPUTATIONS_DB_USER: {{ .Values.postgresqlcomputations.username | quote }}
  PRISM_COMPUTATIONS_DB: {{ .Values.postgresqlcomputations.database | quote }}
  PRISM_ES_STORE_URL: "{{ .Release.Name}}-{{ .Values.defaults.eventStreamURL }}"
  PRISM_COMPUTATIONS_HTTP_HOST: "0.0.0.0"
  PRISM_COMPUTATIONS_HTTP_PORT: {{ .Values.computations.httpPort | quote }}
  PRISM_COMPUTATIONS_LOG_LEVEL: {{ default .Values.defaults.logLevel .Values.computations.logLevel | quote }}
  PRISM_BACKENDS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.backends.host }}:{{ .Values.backends.grpcPort }}"
  PRISM_AUTH_GRPC_URL: "{{ .Release.Name }}-{{ .Values.auth.host }}:{{ .Values.auth.grpcPort }}"
  PRISM_BACKENDS_GRPC_TIMEOUT: ""
  PRISM_BILLING: {{ .Values.billing.enabled | quote }}
  PRISM_COMPUTATIONS_DB_SSL_CERT: ""
  PRISM_COMPUTATIONS_DB_SSL_KEY: ""
  PRISM_COMPUTATIONS_DB_SSL_MODE: "disable"
  PRISM_COMPUTATIONS_DB_SSL_ROOT_CERT: ""
  PRISM_COMPUTATIONS_INSTANCE_ID: ""
  PRISM_SPICEDB_HOST: "{{ .Release.Name }}-{{ .Values.spicedb.host }}"
  PRISM_SPICEDB_PORT: {{ .Values.spicedb.grpc.port | quote }}
  PRISM_UI_BILLING_PERMISSIONS_URL: "http://{{ .Release.Name }}-{{ .Values.billingPermissions.host }}:{{ .Values.billingPermissions.httpPort }}"
  PRISM_UI_DOMAINS_URL: "http://{{ .Release.Name }}-{{ .Values.auth.host }}:{{ .Values.auth.httpPort }}"
  PRISM_UI_USERS_URL: "http://{{ .Release.Name }}-{{ .Values.users.host }}:{{ .Values.users.httpPort }}"
  PRISM_USERS_GRPC_CLIENT_TLS: "false"
  PRISM_USERS_GRPC_TIMEOUT: "1s"
  PRISM_USERS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.users.host }}:{{ .Values.users.grpcPort }}"
  PRISM_SPICEDB_SCHEMA_FILE: {{ .Values.spicedb.schemaFile | quote}}
  PRISM_DOMAINS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.domains.host }}:{{ .Values.domains.grpcPort }}"
  PRISM_DOMAINS_GRPC_TIMEOUT: "10s"

