# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-domains
spec:
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable: 25%
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: domains
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.domains.httpPort }}"
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/domains-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        component: domains
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.domains.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-domains
          image: "{{ default (printf "%s/domains" .Values.defaults.image.rootRepository) .Values.domains.image.repository }}:{{ default .Values.defaults.image.tag .Values.domains.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.domains.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-domains-env-vars
          env:
            - name: SMQ_DOMAINS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-domains-secrets
                  key: SMQ_DOMAINS_DB_USER
            - name: SMQ_DOMAINS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-domains-secrets
                  key: SMQ_DOMAINS_DB_PASS
            - name: SMQ_DOMAINS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-domains-secrets
                  key: SMQ_DOMAINS_DB_NAME
            - name: SMQ_SPICEDB_PRE_SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-spicedb-secrets
                  key: SMQ_SPICEDB_PRE_SHARED_KEY
            - name: SMQ_AUTH_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_CERT
            - name: SMQ_AUTH_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_KEY
            - name: SMQ_AUTH_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-server-certs
                  key: PRISM_AUTH_GRPC_SERVER_CA_CERTS
            - name: SMQ_DOMAINS_GRPC_CLIENT_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS
            - name: SMQ_DOMAINS_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-server-certs
                  key: PRISM_DOMAINS_GRPC_SERVER_CA_CERTS
            - name: SMQ_DOMAINS_GRPC_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-server-certs
                  key: PRISM_DOMAINS_GRPC_SERVER_CERT
            - name: SMQ_DOMAINS_GRPC_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-server-certs
                  key: PRISM_DOMAINS_GRPC_SERVER_KEY
            - name: SMQ_DOMAINS_HTTP_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-server-certs
                  key: PRISM_DOMAINS_HTTP_SERVER_CERT
            - name: SMQ_DOMAINS_HTTP_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-server-certs
                  key: SMQ_DOMAINS_HTTP_SERVER_KEY
            - name: SMQ_DOMAINS_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_KEY
          ports:
            - containerPort: {{ .Values.domains.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.domains.grpcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.domains.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.domains.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /spicedb
              name: spicedb-schema-zed
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: spicedb-schema-zed
          configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-spicedb-schema-zed
            optional: false
