# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-domains
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
    component: domains
  ports:
    - protocol: TCP
      port: {{ .Values.domains.httpPort }}
      name: {{ .Release.Name }}-domains-http
      targetPort: {{ .Values.domains.httpPort }}
    - protocol: TCP
      port: {{ .Values.domains.grpcPort }}
      name: {{ .Release.Name }}-domains-grpc
      targetPort: {{ .Values.domains.grpcPort }}
