# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-domains
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: domains
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.domains.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: domains
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.domains.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-domains
          image: "{{ default (printf "%s/domains" .Values.defaults.image.rootRepository) .Values.domains.image.repository }}:{{ default .Values.defaults.image.tag .Values.domains.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.domains.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-domains-env-vars
          ports:
            - containerPort: {{ .Values.domains.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.domains.grpcPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-domains-ssl-config
              mountPath: /ssl/certs/domains
              readOnly: true
            - mountPath: /spicedb
              name: spicedb-schema-zed
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: {{ .Release.Name }}-domains-ssl-config
          configMap:
            name: {{ .Release.Name }}-domains-ssl-files
        - name: spicedb-schema-zed
          configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-spicedb-schema-zed
            optional: false
      {{- with .Values.domains.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.domains.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.domains.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
