# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-user-email-template-config
  namespace: {{ .Release.Namespace }}
data:
  verification-email.tmpl: |-
{{ include "verification.tmpl" . | indent 4 }}
  invite.tmpl: |-
{{ include "invite.tmpl" . | indent 4 }}
  reset-password-email.tmpl: |-
{{ include "reset.tmpl" . | indent 4 }}
