# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- define "prism.envoy.config" -}}
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.auth.grpcPort }}
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: {{ .Release.Name }}-auth-envoy
                route_config:
                  name: auth_route
                  virtual_hosts:
                    - name: auth_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: {{ .Release.Name }}_auth_cluster
                http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: {{ .Release.Name }}_mqtt_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: {{ .Release.Name }}_mqtt_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Release.Name }}-mqtt
                    port_value: 1884
    - name: {{ .Release.Name }}_auth_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: {{ .Release.Name }}_auth_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Release.Name }}-auth-headless
                    port_value: {{ .Values.auth.grpcPort }}
admin:
    access_log_path: "/dev/null"
    address:
      socket_address:
          address: 0.0.0.0
          port_value: 8001

{{- end -}}