apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_dashboard: "1"
data:
  prism-grafana-dashboard.json: |-
{{ (.Files.Get "files/prism-grafana-dashboard.json") | indent 4 }}
