# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0
{{- range .Values.deployments }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ $.Release.Name }}-{{ . }}-hpa-rollout"
  namespace: {{ $.Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ $.Release.Name }}-{{ . }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
{{- end }}