# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-invitations
spec:
  strategy:
    {{- if .Values.env.prod }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    {{ else }}
    type: Recreate
    {{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: invitations
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.invitations.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: invitations
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.invitations.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-invitations
          image: "{{ default (printf "%s/invitations" .Values.defaults.image.rootRepository) .Values.invitations.image.repository }}:{{ default .Values.defaults.image.tag .Values.invitations.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.invitations.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-invitations-env-vars
          ports:
            - containerPort: {{ .Values.invitations.httpPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.invitations.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.invitations.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"