# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-invitations-env-vars
data:
  SMQ_AUTH_GRPC_CLIENT_CERT: ""
  SMQ_AUTH_GRPC_CLIENT_KEY: ""
  SMQ_AUTH_GRPC_SERVER_CA_CERTS: ""
  SMQ_AUTH_GRPC_TIMEOUT: "10s"
  SMQ_AUTH_GRPC_URL: "{{ .Release.Name }}-{{ .Values.auth.host }}:{{ .Values.auth.grpcPort }}"
  SMQ_DOMAINS_URL: "http://{{ .Values.auth.host }}:{{ .Values.auth.httpPort }}"
  SMQ_INVITATIONS_DB_PORT: {{ .Values.postgresqlinvitations.port | quote }}
  SMQ_INVITATIONS_DB_NAME: {{ .Values.postgresqlinvitations.database | quote }}
  SMQ_INVITATIONS_DB_USER: {{ .Values.postgresqlinvitations.username | quote }}
  SMQ_INVITATIONS_DB_PASS: {{ .Values.postgresqlinvitations.password | quote }}
  SMQ_INVITATIONS_DB_HOST:
    {{- if .Values.postgresqlinvitations.enabled }}
      "{{ .Release.Name }}-postgresqlinvitations"
    {{- else }}:
      {{ .Values.postgresqlinvitations | quote }}
    {{- end }}
  SMQ_INVITATIONS_DB_SSL_CERT: ""
  SMQ_INVITATIONS_DB_SSL_KEY: ""
  SMQ_INVITATIONS_DB_SSL_MODE: "disable"
  SMQ_INVITATIONS_DB_SSL_ROOT_CERT: ""
  SMQ_INVITATIONS_HTTP_HOST: "0.0.0.0"
  SMQ_INVITATIONS_HTTP_PORT: {{ .Values.invitations.httpPort | quote}}
  SMQ_INVITATIONS_HTTP_SERVER_CERT: ""
  SMQ_INVITATIONS_HTTP_SERVER_KEY: ""
  SMQ_INVITATIONS_INSTANCE_ID: ""
  SMQ_INVITATIONS_LOG_LEVEL: "info"
  SMQ_JAEGER_TRACE_RATIO: "1.0"
  SMQ_JAEGER_URL: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.defaults.jaegerCollectorPort }}/v1/traces"
  SMQ_SEND_TELEMETRY: "false"
  SMQ_USERS_URL: "http://{{ .Release.Name }}-{{ .Values.users.host }}:{{ .Values.users.httpPort }}"