# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.jaeger.provisionDataStore.cassandra }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ .Release.Name }}-cassandra-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  hostPath:
    path: /mnt/data

{{- end }}