# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.externalsecrets.enabled }}

# SecretStore that connects to Google Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: prism-gcp-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: prism-gcp-project-id
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: {{ .Release.Namespace }}

---
# Service Account for ESO to authenticate with GCP
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-external-secrets-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: eso-gcp-sa@your-gcp-project-id.iam.gserviceaccount.com

---
# ExternalSecret for am-certs secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-am-certs-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-am-certs-secrets
    creationPolicy: Owner
  data:
    - secretKey: AM_CERTS_DB_USER
      remoteRef:
        key: am-certs-db-user
    - secretKey: AM_CERTS_DB_PASS
      remoteRef:
        key: am-certs-db-pass
    - secretKey: AM_CERTS_DB_NAME
      remoteRef:
        key: am-certs-db-name

---
# ExternalSecret for auth secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-auth-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalsecrets.defaultRefresh }}
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_AUTH_DB_USER
      remoteRef:
        key: prism-auth-db-user
    - secretKey: PRISM_AUTH_DB_PASS
      remoteRef:
        key: prism-auth-db-pass
    - secretKey: PRISM_AUTH_SECRET_KEY
      remoteRef:
        key: prism-auth-secret-key
    - secretKey: PRISM_AUTH_SECRET
      remoteRef:
        key: prism-auth-secret
    - secretKey: PRISM_AUTH_DB_NAME
      remoteRef:
        key: prism-auth-db-name

---
# ExternalSecret for backends secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-backends-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-backends-secrets
    creationPolicy: Owner
  data:
    - secretKey: ARM_SUBSCRIPTION_ID
      remoteRef:
        key: prism-arm-subscription-id
    - secretKey: ARM_CLIENT_ID
      remoteRef:
        key: prism-arm-client-id
    - secretKey: ARM_CLIENT_SECRET
      remoteRef:
        key: prism-arm-client-secret
    - secretKey: ARM_TENANT_ID
      remoteRef:
        key: prism-arm-tenant-id
    - secretKey: PRISM_BACKENDS_DB_USER
      remoteRef:
        key: prism-backends-db-user
    - secretKey: PRISM_BACKENDS_DB_PASS
      remoteRef:
        key: prism-backends-db-pass
    - secretKey: PRISM_BACKENDS_DB_DATABASE
      remoteRef:
        key: prism-backends-db-database
  dataFrom:
    # Google application credentials JSON
    - extract:
        key: google-application-credentials-json
        conversionStrategy: Default  # maintain the JSON structure
      rewrite:
        - regexp:
            source: ".*"
            target: stringData.google_application_credentials.json

---
# ExternalSecret for billing secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-billing-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-billing-secrets
    creationPolicy: Owner
  data:
    - secretKey: MG_BILLING_DB_USER
      remoteRef:
        key: mg-billing-db-user
    - secretKey: MG_BILLING_DB_NAME
      remoteRef:
        key: mg-billing-db-name
    - secretKey: MG_BILLING_DB_PASS
      remoteRef:
        key: mg-billing-db-pass
    - secretKey: MG_BILLING_STRIPE_PK
      remoteRef:
        key: mg-billing-stripe-pk
    - secretKey: MG_BILLING_STRIPE_WEBHOOKSECRET
      remoteRef:
        key: mg-billing-stripe-webhooksecret

---
# ExternalSecret for computations secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-computations-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-computations-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_COMPUTATIONS_DB_USER
      remoteRef:
        key: prism-computations-db-user
    - secretKey: PRISM_COMPUTATIONS_DB_PASS
      remoteRef:
        key: prism-computations-db-pass
    - secretKey: PRISM_COMPUTATIONS_DB_NAME
      remoteRef:
        key: prism-computations-db-name

---
# ExternalSecret for domains secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-domains-external-secret
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-domains-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMQ_DOMAINS_DB_USER
      remoteRef:
        key: smq-domains-db-user
    - secretKey: SMQ_DOMAINS_DB_PASS
      remoteRef:
        key: smq-domains-db-pass
    - secretKey: SMQ_DOMAINS_DB_NAME
      remoteRef:
        key: smq-domains-db-name

---
# ExternalSecret for ui secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-ui-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-ui-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_UI_STRIPE_PK
      remoteRef:
        key: prism-ui-stripe-pk
    - secretKey: PRISM_UI_HASH_KEY
      remoteRef:
        key: prism-ui-hash-key
    - secretKey: PRISM_UI_BLOCK_KEY
      remoteRef:
        key: prism-ui-block-key
    - secretKey: PRISM_EMAIL_PASSWORD
      remoteRef:
        key: prism-email-password
    - secretKey: PRISM_EMAIL_USERNAME
      remoteRef:
        key: prism-email-username
    - secretKey: PRISM_STRIPE_PK
      remoteRef:
        key: prism-stripe-pk

---
# ExternalSecret for users secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-users-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-users-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMQ_USERS_ADMIN_EMAIL
      remoteRef:
        key: smq-users-admin-email
    - secretKey: SMQ_USERS_ADMIN_PASSWORD
      remoteRef:
        key: smq-users-admin-password
    - secretKey: SMQ_USERS_SECRET_KEY
      remoteRef:
        key: smq-users-secret-key
    - secretKey: SMQ_USERS_DB_USER
      remoteRef:
        key: smq-users-db-user
    - secretKey: SMQ_USERS_DB_PASS
      remoteRef:
        key: smq-users-db-pass
    - secretKey: SMQ_USERS_DB_NAME
      remoteRef:
        key: smq-users-db-name
    - secretKey: SMQ_EMAIL_PASSWORD
      remoteRef:
        key: smq-email-password
    - secretKey: SMQ_EMAIL_USERNAME
      remoteRef:
        key: smq-email-username
    - secretKey: SMQ_EMAIL_FROM_ADDRESS
      remoteRef:
        key: smq-email-from-address

---
# ExternalSecret for prometheus/grafana secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-prometheus-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prometheus-secrets
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: grafana-admin-user
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: grafana-admin-password
    - secretKey: ALERT_MANAGER_SLACK_URL
      remoteRef:
        key: alert-manager-slack-url

---
# ExternalSecret for shared SpiceDB secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-shared-spicedb-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-shared-spicedb-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_SPICEDB_PRE_SHARED_KEY
      remoteRef:
        key: prism-spicedb-pre-shared-key

---

# ExternalSecret for shared gRPC server certificates
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-shared-grpc-server-certs-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-shared-grpc-server-certs
    creationPolicy: Owner
  data:
    # AM Certs
    - secretKey: AM_CERTS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: am-certs-grpc-server-ca-certs
    - secretKey: AM_CERTS_GRPC_SERVER_CERT
      remoteRef:
        key: am-certs-grpc-server-cert
    - secretKey: AM_CERTS_GRPC_SERVER_KEY
      remoteRef:
        key: am-certs-grpc-server-key

    # Auth
    - secretKey: PRISM_AUTH_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-auth-grpc-server-ca-certs
    - secretKey: PRISM_AUTH_GRPC_SERVER_CERT
      remoteRef:
        key: prism-auth-grpc-server-cert
    - secretKey: PRISM_AUTH_GRPC_SERVER_KEY
      remoteRef:
        key: prism-auth-grpc-server-key

    # Backends
    - secretKey: PRISM_BACKENDS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-backends-grpc-server-ca-certs
    - secretKey: PRISM_BACKENDS_GRPC_SERVER_CERT
      remoteRef:
        key: prism-backends-grpc-server-cert
    - secretKey: PRISM_BACKENDS_GRPC_SERVER_KEY
      remoteRef:
        key: prism-backends-grpc-server-key
    - secretKey: PRISM_BACKENDS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-backends-http-server-cert
    - secretKey: PRISM_BACKENDS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-backends-http-server-key

    # Manager
    - secretKey: PRISM_MANAGER_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-manager-grpc-server-ca-certs
    - secretKey: PRISM_MANAGER_GRPC_SERVER_CA_KEY
      remoteRef:
        key: prism-manager-grpc-server-ca-key
    - secretKey: PRISM_MANAGER_GRPC_SERVER_CERT
      remoteRef:
        key: prism-manager-grpc-server-cert
    - secretKey: PRISM_MANAGER_GRPC_SERVER_KEY
      remoteRef:
        key: prism-manager-grpc-server-key

    # Billing
    - secretKey: MG_BILLING_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: mg-billing-grpc-server-ca-certs
    - secretKey: MG_BILLING_GRPC_SERVER_CA_KEY
      remoteRef:
        key: mg-billing-grpc-server-ca-key
    - secretKey: MG_BILLING_GRPC_SERVER_CERT
      remoteRef:
        key: mg-billing-grpc-server-cert
    - secretKey: MG_BILLING_GRPC_SERVER_KEY
      remoteRef:
        key: mg-billing-grpc-server-key
    - secretKey: MG_BILLING_SERVER_CERT
      remoteRef:
        key: mg-billing-server-cert
    - secretKey: MG_BILLING_SERVER_KEY
      remoteRef:
        key: mg-billing-server-key

    # Certs
    - secretKey: PRISM_CERTS_GRPC_SERVER_CERT
      remoteRef:
        key: prism-certs-grpc-server-cert
    - secretKey: PRISM_CERTS_GRPC_SERVER_KEY
      remoteRef:
        key: prism-certs-grpc-server-key
    - secretKey: PRISM_CERTS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-certs-grpc-server-ca-certs
    - secretKey: PRISM_CERTS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-certs-http-server-cert
    - secretKey: PRISM_CERTS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-certs-http-server-key

    # Computations
    - secretKey: PRISM_COMPUTATIONS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-computations-http-server-cert
    - secretKey: PRISM_COMPUTATIONS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-computations-http-server-key

    # Domains
    - secretKey: PRISM_DOMAINS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-domains-grpc-server-ca-certs
    - secretKey: PRISM_DOMAINS_GRPC_SERVER_CERT
      remoteRef:
        key: prism-domains-grpc-server-cert
    - secretKey: PRISM_DOMAINS_GRPC_SERVER_KEY
      remoteRef:
        key: prism-domains-grpc-server-key
    - secretKey: PRISM_DOMAINS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-domains-http-server-cert
    - secretKey: PRISM_DOMAINS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-domains-http-server-key

    # Users
    - secretKey: PRISM_USERS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-users-grpc-server-ca-certs
    - secretKey: PRISM_USERS_GRPC_SERVER_CERT
      remoteRef:
        key: prism-users-grpc-server-cert
    - secretKey: PRISM_USERS_GRPC_SERVER_KEY
      remoteRef:
        key: prism-users-grpc-server-key
    - secretKey: PRISM_USERS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-users-http-server-cert
    - secretKey: PRISM_USERS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-users-http-server-key

---
# ExternalSecret for shared gRPC client certificates
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-grpc-client-certs-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-shared-grpc-client-certs
    creationPolicy: Owner
  data:
    # AM Certs
    - secretKey: AM_CERTS_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: am-certs-grpc-client-ca-certs
    - secretKey: AM_CERTS_GRPC_CLIENT_KEY
      remoteRef:
        key: am-certs-grpc-client-KEY
    - secretKey: AM_CERTS_GRPC_CLIENT_CERT
      remoteRef:
        key: am-certs-grpc-client-cERT

    # Auth
    - secretKey: PRISM_AUTH_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-auth-grpc-client-ca-certs
    - secretKey: PRISM_AUTH_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-auth-grpc-client-cert
    - secretKey: PRISM_AUTH_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-auth-grpc-client-key

    # Backends
    - secretKey: PRISM_BACKENDS_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-backends-grpc-client-ca-certs
    - secretKey: PRISM_BACKENDS_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-backends-grpc-client-cert
    - secretKey: PRISM_BACKENDS_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-backends-grpc-client-key

    # Manager
    - secretKey: PRISM_MANAGER_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-manager-grpc-client-ca-certs
    - secretKey: PRISM_MANAGER_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-manager-grpc-client-cert
    - secretKey: PRISM_MANAGER_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-manager-grpc-client-key

    # Billing
    - secretKey: MG_BILLING_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: mg-billing-grpc-client-ca-certs
    - secretKey: MG_BILLING_GRPC_CLIENT_KEY
      remoteRef:
        key: mg-billing-grpc-client-key
    - secretKey: MG_BILLING_GRPC_CLIENT_CERT
      remoteRef:
        key: mg-billing-grpc-client-cert

    # Certs
    - secretKey: PRISM_CERTS_GRPC_CA_CERTS
      remoteRef:
        key: prism-certs-grpc-ca-certs
    - secretKey: PRISM_CERTS_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-certs-grpc-client-cert
    - secretKey: PRISM_CERTS_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-certs-grpc-client-key

    # Domains
    - secretKey: PRISM_DOMAINS_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-domains-grpc-client-cert
    - secretKey: PRISM_DOMAINS_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-domains-grpc-client-key
    - secretKey: PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-domains-grpc-client-ca-certs

    # Users
    - secretKey: PRISM_USERS_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-users-grpc-client-ca-certs
    - secretKey: PRISM_USERS_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-users-grpc-client-cert
    - secretKey: PRISM_USERS_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-users-grpc-client-key

{{- end }}