# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

---
# am-certs secrets
apiVersion: v1
kind: Secret
metadata:
  name: am-certs-secrets
type: Opaque
data:
  AM_CERTS_DB_USER: "${AM_CERTS_DB_USER}"
  AM_CERTS_DB_PASS: "${AM_CERTS_DB_PASS}"
---
# auth secrets
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  PRISM_AUTH_DB_USER: "${PRISM_AUTH_DB_USER}"
  PRISM_AUTH_DB_PASS: "${PRISM_AUTH_DB_PASS}"
  PRISM_AUTH_SECRET_KEY: "${PRISM_AUTH_SECRET_KEY}"
  PRISM_AUTH_SECRET: "${PRISM_AUTH_SECRET}"
---
# backends secrets
apiVersion: v1
kind: Secret
metadata:
  name: backends-secrets
type: Opaque
data:
  PRISM_BACKENDS_DB_USER: "${PRISM_BACKENDS_DB_USER}"
  PRISM_BACKENDS_DB_PASS: "${PRISM_BACKENDS_DB_PASS}"
---
# billing secrets
apiVersion: v1
kind: Secret
metadata:
  name: billing-secrets
type: Opaque
data:
  MG_BILLING_DB_USER: "${MG_BILLING_DB_USER}"
  MG_BILLING_DB_PASS: "${MG_BILLING_DB_PASS}"
  MG_BILLING_STRIPE_PK: "${MG_BILLING_STRIPE_PK}"
  MG_BILLING_STRIPE_WEBHOOKSECRET: "${MG_BILLING_STRIPE_WEBHOOKSECRET}"
---
# computations secrets
apiVersion: v1
kind: Secret
metadata:
  name: computations-secrets
type: Opaque
data:
  PRISM_COMPUTATIONS_DB_USER: "${PRISM_COMPUTATIONS_DB_USER}"
  PRISM_COMPUTATIONS_DB_PASS: "${PRISM_COMPUTATIONS_DB_PASS}"

---
# domains secrets
apiVersion: v1
kind: Secret
metadata:
  name: domains-secrets
type: Opaque
data:
  SMQ_DOMAINS_DB_USER: "${SMQ_DOMAINS_DB_USER}"
  SMQ_DOMAINS_DB_PASS: "${SMQ_DOMAINS_DB_PASS}"
---
# ui secrets
apiVersion: v1
kind: Secret
metadata:
  name: ui-secrets
type: Opaque
data:
  PRISM_UI_STRIPE_PK: "${PRISM_UI_STRIPE_PK}"
  PRISM_UI_HASH_KEY: "${PRISM_UI_HASH_KEY}"
  PRISM_UI_BLOCK_KEY: "${PRISM_UI_BLOCK_KEY}"
  PRISM_EMAIL_PASSWORD: "${PRISM_EMAIL_PASSWORD}"
  PRISM_EMAIL_USERNAME: "${PRISM_EMAIL_USERNAME}"
  PRISM_STRIPE_PK: "${PRISM_STRIPE_PK}"
---
# users secrets
apiVersion: v1
kind: Secret
metadata:
  name: users-secrets
type: Opaque
data:
  SMQ_USERS_ADMIN_EMAIL: "${SMQ_USERS_ADMIN_EMAIL}"
  SMQ_USERS_ADMIN_PASSWORD: "${SMQ_USERS_ADMIN_PASSWORD}"
  SMQ_USERS_SECRET_KEY: "${SMQ_USERS_SECRET_KEY}"
  SMQ_USERS_DB_USER: "${SMQ_USERS_DB_USER}"
  SMQ_USERS_DB_PASS: "${SMQ_USERS_DB_PASS}"
  SMQ_EMAIL_PASSWORD: "${SMQ_EMAIL_PASSWORD}"
  SMQ_EMAIL_FROM_ADDRESS: "${SMQ_EMAIL_FROM_ADDRESS}"
---
# grafana secrets
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secrets
type: Opaque
data:
  GRAFANA_ADMIN_USER: "${ADMIN_USER}"
  GRAFANA_ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
  ALERT_MANAGER_SLACK_URL: "${ALERT_MANAGER_SLACK_URL}"
---
# Shared secrets - SpiceDB
apiVersion: v1
kind: Secret
metadata:
  name: shared-spicedb-secrets
type: Opaque
data:
  PRISM_SPICEDB_PRE_SHARED_KEY: "${PRISM_SPICEDB_PRE_SHARED_KEY}"
---
# Shared TLS/gRPC certificates - Server certificates
apiVersion: v1
kind: Secret
metadata:
  name: shared-grpc-server-certs
type: Opaque
data:
  # AM Certs
  AM_CERTS_GRPC_SERVER_CA_CERTS: "${AM_CERTS_GRPC_SERVER_CA_CERTS}"
  AM_CERTS_GRPC_SERVER_CERT: "${AM_CERTS_GRPC_SERVER_CERT}"
  AM_CERTS_GRPC_SERVER_KEY: "${AM_CERTS_GRPC_SERVER_KEY}"

  # Auth
  PRISM_AUTH_GRPC_SERVER_CA_CERTS: "${PRISM_AUTH_GRPC_SERVER_CA_CERTS}"
  PRISM_AUTH_GRPC_SERVER_CERT: "${PRISM_AUTH_GRPC_SERVER_CERT}"
  PRISM_AUTH_GRPC_SERVER_KEY: "${PRISM_AUTH_GRPC_SERVER_KEY}"

  # Backends
  PRISM_BACKENDS_GRPC_SERVER_CA_CERTS: "${PRISM_BACKENDS_GRPC_SERVER_CA_CERTS}"
  PRISM_BACKENDS_GRPC_SERVER_CERT: "${PRISM_BACKENDS_GRPC_SERVER_CERT}"
  PRISM_BACKENDS_GRPC_SERVER_KEY: "${PRISM_BACKENDS_GRPC_SERVER_KEY}"
  PRISM_BACKENDS_HTTP_SERVER_CERT: "${PRISM_BACKENDS_HTTP_SERVER_CERT}"
  PRISM_BACKENDS_HTTP_SERVER_KEY: "${PRISM_BACKENDS_HTTP_SERVER_KEY}"

  # Manager
  PRISM_MANAGER_GRPC_SERVER_CA_CERTS: "${PRISM_MANAGER_GRPC_SERVER_CA_CERTS}"
  PRISM_MANAGER_GRPC_SERVER_CA_KEY: "${PRISM_MANAGER_GRPC_SERVER_CA_KEY}"
  PRISM_MANAGER_GRPC_SERVER_CERT: "${PRISM_MANAGER_GRPC_SERVER_CERT}"
  PRISM_MANAGER_GRPC_SERVER_KEY: "${PRISM_MANAGER_GRPC_SERVER_KEY}"

  # Billing
  MG_BILLING_GRPC_SERVER_CA_CERTS: "${MG_BILLING_GRPC_SERVER_CA_CERTS}"
  MG_BILLING_GRPC_SERVER_CA_KEY: "${MG_BILLING_GRPC_SERVER_CA_KEY}"
  MG_BILLING_GRPC_SERVER_CERT: "${MG_BILLING_GRPC_SERVER_CERT}"
  MG_BILLING_GRPC_SERVER_KEY: "${MG_BILLING_GRPC_SERVER_KEY}"
  MG_BILLING_SERVER_CERT: "${MG_BILLING_SERVER_CERT}"
  MG_BILLING_SERVER_KEY: "${MG_BILLING_SERVER_KEY}"

  # Certs
  CERTS_GRPC_SERVER_CERT: "${CERTS_GRPC_SERVER_CERT}"
  CERTS_GRPC_SERVER_KEY: "${CERTS_GRPC_SERVER_KEY}"
  CERTS_GRPC_SERVER_CA_CERTS: "${CERTS_GRPC_SERVER_CA_CERTS}"
  PRISM_CERTS_HTTP_SERVER_CERT: "${PRISM_CERTS_HTTP_SERVER_CERT}"
  PRISM_CERTS_HTTP_SERVER_KEY: "${PRISM_CERTS_HTTP_SERVER_KEY}"

  # Computations
  PRISM_COMPUTATIONS_HTTP_SERVER_CERT: "${PRISM_COMPUTATIONS_HTTP_SERVER_CERT}"
  PRISM_COMPUTATIONS_HTTP_SERVER_KEY: "${PRISM_COMPUTATIONS_HTTP_SERVER_KEY}"

  # Domains
  SMQ_DOMAINS_GRPC_SERVER_CA_CERTS: "${SMQ_DOMAINS_GRPC_SERVER_CA_CERTS}"
  SMQ_DOMAINS_GRPC_SERVER_CERT: "${SMQ_DOMAINS_GRPC_SERVER_CERT}"
  SMQ_DOMAINS_GRPC_SERVER_KEY: "${SMQ_DOMAINS_GRPC_SERVER_KEY}"
  SMQ_DOMAINS_HTTP_SERVER_CERT: "${SMQ_DOMAINS_HTTP_SERVER_CERT}"
  SMQ_DOMAINS_HTTP_SERVER_KEY: "${SMQ_DOMAINS_HTTP_SERVER_KEY}"

  # Users
  SMQ_USERS_GRPC_SERVER_CA_CERTS: "${SMQ_USERS_GRPC_SERVER_CA_CERTS}"
  SMQ_USERS_GRPC_SERVER_CERT: "${SMQ_USERS_GRPC_SERVER_CERT}"
  SMQ_USERS_GRPC_SERVER_KEY: "${SMQ_USERS_GRPC_SERVER_KEY}"
  SMQ_USERS_HTTP_SERVER_CERT: "${SMQ_USERS_HTTP_SERVER_CERT}"
  SMQ_USERS_HTTP_SERVER_KEY: "${SMQ_USERS_HTTP_SERVER_KEY}"
---
# Shared TLS/gRPC certificates - Client certificates
apiVersion: v1
kind: Secret
metadata:
  name: shared-grpc-client-certs
type: Opaque
data:
  # AM Certs
  AM_CERTS_GRPC_CLIENT_CA_CERTS: "${AM_CERTS_GRPC_CLIENT_CA_CERTS}"

  # Auth
  PRISM_AUTH_GRPC_CLIENT_CA_CERTS: "${PRISM_AUTH_GRPC_CLIENT_CA_CERTS}"
  PRISM_AUTH_GRPC_CLIENT_CERT: "${PRISM_AUTH_GRPC_CLIENT_CERT}"
  PRISM_AUTH_GRPC_CLIENT_KEY: "${PRISM_AUTH_GRPC_CLIENT_KEY}"

  # Backends
  PRISM_BACKENDS_GRPC_CLIENT_CA_CERTS: "${PRISM_BACKENDS_GRPC_CLIENT_CA_CERTS}"
  PRISM_BACKENDS_GRPC_CLIENT_CERT: "${PRISM_BACKENDS_GRPC_CLIENT_CERT}"
  PRISM_BACKENDS_GRPC_CLIENT_KEY: "${PRISM_BACKENDS_GRPC_CLIENT_KEY}"

  # Manager
  PRISM_MANAGER_GRPC_CLIENT_CA_CERTS: "${PRISM_MANAGER_GRPC_CLIENT_CA_CERTS}"

  # Billing
  MG_BILLING_GRPC_CLIENT_CA_CERTS: "${MG_BILLING_GRPC_CLIENT_CA_CERTS}"

  # Certs
  PRISM_CERTS_GRPC_CA_CERTS: "${PRISM_CERTS_GRPC_CA_CERTS}"
  PRISM_CERTS_GRPC_CLIENT_CERT: "${PRISM_CERTS_GRPC_CLIENT_CERT}"
  PRISM_CERTS_GRPC_CLIENT_KEY: "${PRISM_CERTS_GRPC_CLIENT_KEY}"
  CERTS_GRPC_CA_CERTS: "${CERTS_GRPC_CA_CERTS}"
  CERTS_GRPC_CLIENT_CA_CERTS: "${CERTS_GRPC_CLIENT_CA_CERTS}"
  CERTS_GRPC_CLIENT_CERT: "${CERTS_GRPC_CLIENT_CERT}"
  CERTS_GRPC_CLIENT_KEY: "${CERTS_GRPC_CLIENT_KEY}"

  # Domains
  PRISM_DOMAINS_GRPC_CLIENT_CERT: "${PRISM_DOMAINS_GRPC_CLIENT_CERT}"
  PRISM_DOMAINS_GRPC_CLIENT_KEY: "${PRISM_DOMAINS_GRPC_CLIENT_KEY}"
  PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS: "${PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS}"
  MG_DOMAINS_GRPC_CLIENT_CERT: "${MG_DOMAINS_GRPC_CLIENT_CERT}"
  MG_DOMAINS_GRPC_CLIENT_KEY: "${MG_DOMAINS_GRPC_CLIENT_KEY}"
  MG_DOMAINS_GRPC_CLIENT_CA_CERTS: "${MG_DOMAINS_GRPC_CLIENT_CA_CERTS}"
  SMQ_DOMAINS_GRPC_CLIENT_CA_CERTS: "${SMQ_DOMAINS_GRPC_CLIENT_CA_CERTS}"
  SMQ_DOMAINS_GRPC_CLIENT_CERT: "${SMQ_DOMAINS_GRPC_CLIENT_CERT}"
  SMQ_DOMAINS_GRPC_CLIENT_KEY: "${SMQ_DOMAINS_GRPC_CLIENT_KEY}"

  # Users
  PRISM_USERS_GRPC_CA_CERTS: "${PRISM_USERS_GRPC_CA_CERTS}"
  SMQ_USERS_GRPC_CLIENT_CA_CERTS: "${SMQ_USERS_GRPC_CLIENT_CA_CERTS}"

  # Auth client certs needed by other services
  SMQ_AUTH_GRPC_CLIENT_CERT: "${SMQ_AUTH_GRPC_CLIENT_CERT}"
  SMQ_AUTH_GRPC_CLIENT_KEY: "${SMQ_AUTH_GRPC_CLIENT_KEY}"
  SMQ_AUTH_GRPC_SERVER_CA_CERTS: "${SMQ_AUTH_GRPC_SERVER_CA_CERTS}"