# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.externalsecrets.enabled }}

# SecretStore that connects to Google Secret Manager
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: prism-gcp-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: valued-base-354714
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credential

---
apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
  namespace: {{ .Release.Namespace }}
  labels:
    type: gcpsm
type: Opaque
stringData:
  secret-access-credential: |
    {}
---
# ExternalSecret for am-certs secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-am-certs-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-am-certs-secrets
    creationPolicy: Owner
  data:
    - secretKey: AM_CERTS_DB_PASS
      remoteRef:
        key: am-certs-db-pass

---
# ExternalSecret for auth secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-auth-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalsecrets.defaultRefresh }}
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_AUTH_DB_PASS
      remoteRef:
        key: prism-auth-db-pass
    - secretKey: PRISM_AUTH_SECRET_KEY
      remoteRef:
        key: prism-auth-secret-key
    - secretKey: PRISM_AUTH_SECRET
      remoteRef:
        key: prism-auth-secret

---
# ExternalSecret for backends secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-backends-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-backends-secrets
    creationPolicy: Owner
  data:
    - secretKey: INFRACOST_API_KEY
      remoteRef:
        key: infracost-api-key
    - secretKey: PRISM_BACKENDS_DB_PASS
      remoteRef:
        key: prism-backends-db-pass

---
# ExternalSecret for google billing secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-google-cloud-billing-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-google-cloud-billing-secrets
    creationPolicy: Owner
  data:
    - secretKey: PROJECT_ID
      remoteRef:
        key: project-id
    - secretKey: DATASET_ID
      remoteRef:
        key: dataset-id
    - secretKey: TABLE_ID
      remoteRef:
        key: table-id

---
# ExternalSecret for google cloud secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-google-cloud-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-google-cloud-secrets
    creationPolicy: Owner
  dataFrom:
    # Google application credentials JSON
    - extract:
        key: google-application-credentials-json
        conversionStrategy: Default  # maintain the JSON structure
      rewrite:
        - regexp:
            source: ".*"
            target: stringData.google_application_credentials.json

---
# ExternalSecret for azure secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-azure-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-azure-secrets
    creationPolicy: Owner
  data:
    - secretKey: ARM_SUBSCRIPTION_ID
      remoteRef:
        key: arm-subscription-id
    - secretKey: ARM_CLIENT_ID
      remoteRef:
        key: arm-client-id
    - secretKey: ARM_CLIENT_SECRET
      remoteRef:
        key: arm-client-secret
    - secretKey: ARM_TENANT_ID
      remoteRef:
        key: arm-tenant-id

---
# ExternalSecret for billing secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-billing-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-billing-secrets
    creationPolicy: Owner
  data:
    - secretKey: MG_BILLING_DB_PASS
      remoteRef:
        key: mg-billing-db-pass
    - secretKey: MG_BILLING_STRIPE_PK
      remoteRef:
        key: mg-billing-stripe-pk
    - secretKey: MG_BILLING_STRIPE_WEBHOOKSECRET
      remoteRef:
        key: mg-billing-stripe-webhooksecret

---
# ExternalSecret for cvm-billing secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-cvm-billing-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-cvm-billing-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_CVM_BILLING_DB_PASS
      remoteRef:
        key: prism-cvm-billing-db-pass

---
# ExternalSecret for paddle secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-paddle-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-paddle-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_BILLING_PADDLE_AGGREGATOR_PK
      remoteRef:
        key: prism-billing-paddle-aggregator-pk
    - secretKey: PRISM_BILLING_PADDLE_WEBHOOKSECRET
      remoteRef:
        key: prism-billing-paddle-webhooksecret
    - secretKey: PRISM_PADDLE_CLIENT_TOKEN
      remoteRef:
        key: prism-paddle-client-token

---
# ExternalSecret for computations secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-computations-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-computations-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_COMPUTATIONS_DB_USER
      remoteRef:
        key: prism-computations-db-user
    - secretKey: PRISM_COMPUTATIONS_DB_PASS
      remoteRef:
        key: prism-computations-db-pass
    - secretKey: PRISM_COMPUTATIONS_DB_NAME
      remoteRef:
        key: prism-computations-db-name

---
# ExternalSecret for domains secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-domains-external-secret
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-domains-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMQ_DOMAINS_DB_PASS
      remoteRef:
        key: smq-domains-db-pass

---
# ExternalSecret for spicedb db secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-spicedb-db-secrets-external-secret
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-spicedb-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_SPICEDB_DB_PASS
      remoteRef:
        key: prism-spicedb-db-pass
    - secretKey: SPICEDB_DATASTORE_URI
      remoteRef:
        key: prism-spicedb-datastore-uri

---
# ExternalSecret for ui secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-ui-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-ui-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_UI_STRIPE_PK
      remoteRef:
        key: prism-ui-stripe-pk
    - secretKey: PRISM_UI_HASH_KEY
      remoteRef:
        key: prism-ui-hash-key
    - secretKey: PRISM_UI_BLOCK_KEY
      remoteRef:
        key: prism-ui-block-key
    - secretKey: PRISM_EMAIL_PASSWORD
      remoteRef:
        key: prism-email-password
    - secretKey: PRISM_EMAIL_USERNAME
      remoteRef:
        key: prism-email-username
    - secretKey: PRISM_STRIPE_PK
      remoteRef:
        key: prism-stripe-pk

---
# ExternalSecret for users secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-users-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-users-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMQ_USERS_ADMIN_EMAIL
      remoteRef:
        key: smq-users-admin-email
    - secretKey: SMQ_USERS_ADMIN_PASSWORD
      remoteRef:
        key: smq-users-admin-password
    - secretKey: SMQ_USERS_SECRET_KEY
      remoteRef:
        key: smq-users-secret-key
    - secretKey: SMQ_USERS_DB_USER
      remoteRef:
        key: smq-users-db-user
    - secretKey: SMQ_USERS_DB_PASS
      remoteRef:
        key: smq-users-db-pass
    - secretKey: SMQ_USERS_DB_NAME
      remoteRef:
        key: smq-users-db-name
    - secretKey: SMQ_EMAIL_PASSWORD
      remoteRef:
        key: smq-email-password
    - secretKey: SMQ_EMAIL_USERNAME
      remoteRef:
        key: smq-email-username
    - secretKey: SMQ_EMAIL_FROM_ADDRESS
      remoteRef:
        key: smq-email-from-address

---
# ExternalSecret for prometheus/grafana secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-prometheus-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prometheus-secrets
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: grafana-admin-user
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: grafana-admin-password
    - secretKey: ALERT_MANAGER_SLACK_URL
      remoteRef:
        key: alert-manager-slack-url

---
# ExternalSecret for shared SpiceDB secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-shared-spicedb-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalsecrets.defaultRefresh }}"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-shared-spicedb-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRISM_SPICEDB_PRE_SHARED_KEY
      remoteRef:
        key: prism-spicedb-pre-shared-key

---

# ExternalSecret for shared gRPC server certificates
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prism-shared-grpc-server-certs-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-shared-grpc-server-certs
    creationPolicy: Owner
  data:
    # AM Certs
    - secretKey: AM_CERTS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: am-certs-grpc-server-ca-certs
    - secretKey: AM_CERTS_GRPC_SERVER_CERT
      remoteRef:
        key: am-certs-grpc-server-cert
    - secretKey: AM_CERTS_GRPC_SERVER_KEY
      remoteRef:
        key: am-certs-grpc-server-key

    # Auth
    - secretKey: PRISM_AUTH_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-auth-grpc-server-ca-certs
    - secretKey: PRISM_AUTH_GRPC_SERVER_CERT
      remoteRef:
        key: prism-auth-grpc-server-cert
    - secretKey: PRISM_AUTH_GRPC_SERVER_KEY
      remoteRef:
        key: prism-auth-grpc-server-key

    # Backends
    - secretKey: PRISM_BACKENDS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-backends-grpc-server-ca-certs
    - secretKey: PRISM_BACKENDS_GRPC_SERVER_CERT
      remoteRef:
        key: prism-backends-grpc-server-cert
    - secretKey: PRISM_BACKENDS_GRPC_SERVER_KEY
      remoteRef:
        key: prism-backends-grpc-server-key
    - secretKey: PRISM_BACKENDS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-backends-http-server-cert
    - secretKey: PRISM_BACKENDS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-backends-http-server-key

    # Manager
    - secretKey: PRISM_MANAGER_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-manager-grpc-server-ca-certs
    - secretKey: PRISM_MANAGER_GRPC_SERVER_CA_KEY
      remoteRef:
        key: prism-manager-grpc-server-ca-key
    - secretKey: PRISM_MANAGER_GRPC_SERVER_CERT
      remoteRef:
        key: prism-manager-grpc-server-cert
    - secretKey: PRISM_MANAGER_GRPC_SERVER_KEY
      remoteRef:
        key: prism-manager-grpc-server-key

    # Billing
    - secretKey: MG_BILLING_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: mg-billing-grpc-server-ca-certs
    - secretKey: MG_BILLING_GRPC_SERVER_CA_KEY
      remoteRef:
        key: mg-billing-grpc-server-ca-key
    - secretKey: MG_BILLING_GRPC_SERVER_CERT
      remoteRef:
        key: mg-billing-grpc-server-cert
    - secretKey: MG_BILLING_GRPC_SERVER_KEY
      remoteRef:
        key: mg-billing-grpc-server-key
    - secretKey: MG_BILLING_SERVER_CERT
      remoteRef:
        key: mg-billing-server-cert
    - secretKey: MG_BILLING_SERVER_KEY
      remoteRef:
        key: mg-billing-server-key

    # Certs
    - secretKey: PRISM_CERTS_GRPC_SERVER_CERT
      remoteRef:
        key: prism-certs-grpc-server-cert
    - secretKey: PRISM_CERTS_GRPC_SERVER_KEY
      remoteRef:
        key: prism-certs-grpc-server-key
    - secretKey: PRISM_CERTS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-certs-grpc-server-ca-certs
    - secretKey: PRISM_CERTS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-certs-http-server-cert
    - secretKey: PRISM_CERTS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-certs-http-server-key

    # Computations
    - secretKey: PRISM_COMPUTATIONS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-computations-http-server-cert
    - secretKey: PRISM_COMPUTATIONS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-computations-http-server-key

    # Domains
    - secretKey: PRISM_DOMAINS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-domains-grpc-server-ca-certs
    - secretKey: PRISM_DOMAINS_GRPC_SERVER_CERT
      remoteRef:
        key: prism-domains-grpc-server-cert
    - secretKey: PRISM_DOMAINS_GRPC_SERVER_KEY
      remoteRef:
        key: prism-domains-grpc-server-key
    - secretKey: PRISM_DOMAINS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-domains-http-server-cert
    - secretKey: PRISM_DOMAINS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-domains-http-server-key

    # Users
    - secretKey: PRISM_USERS_GRPC_SERVER_CA_CERTS
      remoteRef:
        key: prism-users-grpc-server-ca-certs
    - secretKey: PRISM_USERS_GRPC_SERVER_CERT
      remoteRef:
        key: prism-users-grpc-server-cert
    - secretKey: PRISM_USERS_GRPC_SERVER_KEY
      remoteRef:
        key: prism-users-grpc-server-key
    - secretKey: PRISM_USERS_HTTP_SERVER_CERT
      remoteRef:
        key: prism-users-http-server-cert
    - secretKey: PRISM_USERS_HTTP_SERVER_KEY
      remoteRef:
        key: prism-users-http-server-key

---
# ExternalSecret for shared gRPC client certificates
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shared-grpc-client-certs-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: prism-gcp-secret-store
    kind: SecretStore
  target:
    name: prism-shared-grpc-client-certs
    creationPolicy: Owner
  data:
    # AM Certs
    - secretKey: AM_CERTS_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: am-certs-grpc-client-ca-certs
    - secretKey: AM_CERTS_GRPC_CLIENT_KEY
      remoteRef:
        key: am-certs-grpc-client-KEY
    - secretKey: AM_CERTS_GRPC_CLIENT_CERT
      remoteRef:
        key: am-certs-grpc-client-cERT

    # Auth
    - secretKey: PRISM_AUTH_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-auth-grpc-client-ca-certs
    - secretKey: PRISM_AUTH_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-auth-grpc-client-cert
    - secretKey: PRISM_AUTH_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-auth-grpc-client-key

    # Backends
    - secretKey: PRISM_BACKENDS_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-backends-grpc-client-ca-certs
    - secretKey: PRISM_BACKENDS_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-backends-grpc-client-cert
    - secretKey: PRISM_BACKENDS_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-backends-grpc-client-key

    # Manager
    - secretKey: PRISM_MANAGER_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-manager-grpc-client-ca-certs
    - secretKey: PRISM_MANAGER_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-manager-grpc-client-cert
    - secretKey: PRISM_MANAGER_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-manager-grpc-client-key

    # Billing
    - secretKey: MG_BILLING_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: mg-billing-grpc-client-ca-certs
    - secretKey: MG_BILLING_GRPC_CLIENT_KEY
      remoteRef:
        key: mg-billing-grpc-client-key
    - secretKey: MG_BILLING_GRPC_CLIENT_CERT
      remoteRef:
        key: mg-billing-grpc-client-cert

    # Certs
    - secretKey: PRISM_CERTS_GRPC_CA_CERTS
      remoteRef:
        key: prism-certs-grpc-ca-certs
    - secretKey: PRISM_CERTS_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-certs-grpc-client-cert
    - secretKey: PRISM_CERTS_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-certs-grpc-client-key

    # Domains
    - secretKey: PRISM_DOMAINS_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-domains-grpc-client-cert
    - secretKey: PRISM_DOMAINS_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-domains-grpc-client-key
    - secretKey: PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-domains-grpc-client-ca-certs

    # Users
    - secretKey: PRISM_USERS_GRPC_CLIENT_CA_CERTS
      remoteRef:
        key: prism-users-grpc-client-ca-certs
    - secretKey: PRISM_USERS_GRPC_CLIENT_CERT
      remoteRef:
        key: prism-users-grpc-client-cert
    - secretKey: PRISM_USERS_GRPC_CLIENT_KEY
      remoteRef:
        key: prism-users-grpc-client-key

{{- end }}