# Copyright (c) Ultraviolet
  # SPDX-License-Identifier: Apache-2.0

---
# am-certs secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-am-certs-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AM_CERTS_DB_PASS: "prism"

---
# auth secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-auth-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PRISM_AUTH_DB_PASS: "magistrala"
  PRISM_AUTH_SECRET_KEY: "HyE2D4RUt9nnKG6v8zKEqAp6g6ka8hhZsqUpzgKvnwpXrNVQSH"
  PRISM_AUTH_SECRET: "supersecret"

---
# azure
apiVersion: v1
kind: Secret
metadata:
  name: prism-azure-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ARM_SUBSCRIPTION_ID: ""
  ARM_CLIENT_ID: ""
  ARM_CLIENT_SECRET: ""
  ARM_TENANT_ID: ""

---
# backends
apiVersion: v1
kind: Secret
metadata:
  name: prism-backends-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  INFRACOST_API_KEY: ""
  PRISM_BACKENDS_DB_PASS: "prism"
---

# google cloud
apiVersion: v1
kind: Secret
metadata:
  name: prism-google-cloud-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  google_application_credentials.json: |
    {}

---
apiVersion: v1
kind: Secret
metadata:
  name: prism-google-cloud-billing-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PROJECT_ID: ""
  DATASET_ID: ""
  TABLE_ID: ""
---
# billing secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-billing-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MG_BILLING_DB_PASS: "prism"
  MG_BILLING_STRIPE_PK: "sk_test_51OP5fhKJ4T6nhCLX8alZqR6UBHoYO5Vdo9zYBIryT8sYgxbIfnRQ32ohRFGVEN6YheVeRwuR7KnjnkxOK68LBJCg00xP6XrnCm"
  MG_BILLING_STRIPE_WEBHOOKSECRET: "whsec_d5c19496cfe0b715abd73c93262d856e44e8d9c3bd9f93b462023db3a5dde670"
---

# cvm-billing secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-cvm-billing-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PRISM_CVM_BILLING_DB_PASS: "prism"
---

# paddle secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-paddle-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PRISM_BILLING_PADDLE_AGGREGATOR_PK: ""
  PRISM_BILLING_PADDLE_WEBHOOKSECRET: ""
  PRISM_PADDLE_CLIENT_TOKEN: ""
---
# computations secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-computations-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PRISM_COMPUTATIONS_DB_PASS: "prism"

---
# domains secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-domains-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SMQ_DOMAINS_DB_PASS: "prism"

---
{{- $databaseHost := .Values.postgresqlspicedb.host | quote }}
{{- if .Values.postgresqlspicedb.enabled }}
  {{- $databaseHost = printf "%s-postgresqlspicedb" .Release.Name }}
{{- end }}

# spicedb secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-spicedb-db-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PRISM_SPICEDB_DB_PASS: "magistrala"
  SPICEDB_DATASTORE_URI: "postgres://{{ .Values.postgresqlspicedb.username }}:magistrala@{{ $databaseHost }}:{{ .Values.postgresqlspicedb.port }}/{{ .Values.postgresqlspicedb.database }}"
---
# ui secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-ui-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PRISM_UI_STRIPE_PK: "pk_test_51OP5fhKJ4T6nhCLXIyYDoLtg4IuhVP87YUjuSDCx6YGgfyPOcmU8WvPhHqUGdaKocYsRVe5gOIUdZuIoAcpbazn800pAvKmIgh"
  PRISM_UI_HASH_KEY: "5jx4x2Qg9OUmzpP5dbveWQ"
  PRISM_UI_BLOCK_KEY: "UtgZjr92jwRY6SPUndHXiyl9QY8qTUyZ"
  PRISM_EMAIL_PASSWORD: "email_password"
  PRISM_EMAIL_USERNAME: "adminemail@gmail.com"
  PRISM_STRIPE_PK: "pk_test_51OP5fhKJ4T6nhCLXIyYDoLtg4IuhVP87YUjuSDCx6YGgfyPOcmU8WvPhHqUGdaKocYsRVe5gOIUdZuIoAcpbazn800pAvKmIgh"
---
# users secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-users-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SMQ_USERS_ADMIN_EMAIL: "admin@example.com"
  SMQ_USERS_ADMIN_PASSWORD: "12345678"
  SMQ_USERS_SECRET_KEY: "secretKey"
  SMQ_USERS_DB_USER: "prism"
  SMQ_USERS_DB_PASS: "prism"
  SMQ_USERS_DB_NAME: "users"
  SMQ_EMAIL_PASSWORD: "email_password"
  SMQ_EMAIL_USERNAME: "adminemail@gmail.com"
  SMQ_EMAIL_FROM_ADDRESS: "adminemail@gmail.com"
---
# grafana secrets
apiVersion: v1
kind: Secret
metadata:
  name: prism-prometheus-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GRAFANA_ADMIN_USER: "prism"
  GRAFANA_ADMIN_PASSWORD: "prism"
  ALERT_MANAGER_SLACK_URL: ""
---
# Shared secrets - SpiceDB
apiVersion: v1
kind: Secret
metadata:
  name: prism-shared-spicedb-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PRISM_SPICEDB_PRE_SHARED_KEY: "12345678"
---

# Shared TLS/gRPC certificates - Server certificates
apiVersion: v1
kind: Secret
metadata:
  name: prism-shared-grpc-server-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # AM Certs
  AM_CERTS_GRPC_SERVER_CA_CERTS: ""
  AM_CERTS_GRPC_SERVER_CERT: ""
  AM_CERTS_GRPC_SERVER_KEY: ""

  # Auth
  PRISM_AUTH_GRPC_SERVER_CA_CERTS: ""
  PRISM_AUTH_GRPC_SERVER_CERT: ""
  PRISM_AUTH_GRPC_SERVER_KEY: ""

  # Backends
  PRISM_BACKENDS_GRPC_SERVER_CA_CERTS: ""
  PRISM_BACKENDS_GRPC_SERVER_CERT: ""
  PRISM_BACKENDS_GRPC_SERVER_KEY: ""
  PRISM_BACKENDS_HTTP_SERVER_CERT: ""
  PRISM_BACKENDS_HTTP_SERVER_KEY: ""

  # Manager
  PRISM_MANAGER_GRPC_SERVER_CA_CERTS: ""
  PRISM_MANAGER_GRPC_SERVER_CA_KEY: ""
  PRISM_MANAGER_GRPC_SERVER_CERT: ""
  PRISM_MANAGER_GRPC_SERVER_KEY: ""

  # Billing
  MG_BILLING_GRPC_SERVER_CA_CERTS: ""
  MG_BILLING_GRPC_SERVER_CA_KEY: ""
  MG_BILLING_GRPC_SERVER_CERT: ""
  MG_BILLING_GRPC_SERVER_KEY: ""
  MG_BILLING_SERVER_CERT: ""
  MG_BILLING_SERVER_KEY: ""

  # Certs
  PRISM_CERTS_GRPC_SERVER_CERT: ""
  PRISM_CERTS_GRPC_SERVER_KEY: ""
  PRISM_CERTS_GRPC_SERVER_CA_CERTS: ""
  PRISM_CERTS_HTTP_SERVER_CERT: ""
  PRISM_CERTS_HTTP_SERVER_KEY: ""

  # Computations
  PRISM_COMPUTATIONS_HTTP_SERVER_CERT: ""
  PRISM_COMPUTATIONS_HTTP_SERVER_KEY: ""

  # Domains
  PRISM_DOMAINS_GRPC_SERVER_CA_CERTS: ""
  PRISM_DOMAINS_GRPC_SERVER_CERT: ""
  PRISM_DOMAINS_GRPC_SERVER_KEY: ""
  PRISM_DOMAINS_HTTP_SERVER_CERT: ""
  PRISM_DOMAINS_HTTP_SERVER_KEY: ""

  # Users
  PRISM_USERS_GRPC_SERVER_CA_CERTS: ""
  PRISM_USERS_GRPC_SERVER_CERT: ""
  PRISM_USERS_GRPC_SERVER_KEY: ""
  PRISM_USERS_HTTP_SERVER_CERT: ""
  PRISM_USERS_HTTP_SERVER_KEY: ""

  # Callouts
  PRISM_CALLOUT_CA_CERT: ""
  PRISM_CALLOUT_CERT: ""
  PRISM_CALLOUT_KEY: ""
---
# Shared TLS/gRPC certificates - Client certificates
apiVersion: v1
kind: Secret
metadata:
  name: prism-shared-grpc-client-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # AM Certs
  AM_CERTS_GRPC_CLIENT_CA_CERTS: ""
  AM_CERTS_GRPC_CLIENT_CERT: ""
  AM_CERTS_GRPC_CLIENT_KEY: ""


  # Auth
  PRISM_AUTH_GRPC_CLIENT_CA_CERTS: ""
  PRISM_AUTH_GRPC_CLIENT_CERT: ""
  PRISM_AUTH_GRPC_CLIENT_KEY: ""

  # Backends
  PRISM_BACKENDS_GRPC_CLIENT_CA_CERTS: ""
  PRISM_BACKENDS_GRPC_CLIENT_CERT: ""
  PRISM_BACKENDS_GRPC_CLIENT_KEY: ""

  # Manager
  PRISM_MANAGER_GRPC_CLIENT_CA_CERTS: ""
  PRISM_MANAGER_GRPC_CLIENT_CERT: ""
  PRISM_MANAGER_GRPC_CLIENT_KEY: ""

  # Billing
  MG_BILLING_GRPC_CLIENT_CA_CERTS: ""
  MG_BILLING_GRPC_CLIENT_KEY: ""
  MG_BILLING_GRPC_CLIENT_CERT: ""

  # Certs
  PRISM_CERTS_GRPC_CA_CERTS: ""
  PRISM_CERTS_GRPC_CLIENT_CERT: ""
  PRISM_CERTS_GRPC_CLIENT_KEY: ""

  # Domains
  PRISM_DOMAINS_GRPC_CLIENT_CERT: ""
  PRISM_DOMAINS_GRPC_CLIENT_KEY: ""
  PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS: ""


  # Users
  PRISM_USERS_GRPC_CLIENT_CA_CERTS: ""
  PRISM_USERS_GRPC_CLIENT_CERT: ""
  PRISM_USERS_GRPC_CLIENT_KEY: ""
