# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- define "providers.azure.toml" -}}

name = "azure"
description = ""

[config]
    resource_group = ""
    location = "eastus"
    subscription_id = "909297de-0577-48a3-a09e-2aa8887d00f9"
    vcpus = [
        2,
        4,
        8,
        16,
        32,
        48,
        64,
        96,
    ]

{{- end -}}
