# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- define "providers.manager.toml" -}}

name = "manager"
description = ""

[config]
    url  = "109.92.195.153:6101"
    client_cert = ""
    client_key = ""
    ca = ""


{{- end -}}
