# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prism-dev-role
  namespace: prism-dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prism-dev-role-binding
  namespace: prism-dev
subjects:
  - kind: ServiceAccount
    name: default
    namespace: prism-dev
roleRef:
  kind: Role
  name: prism-dev-role
  apiGroup: rbac.authorization.k8s.io
