# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prism-dev-role-binding
  namespace: prism-dev
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "prism-dev"
    meta.helm.sh/release-namespace: "prism-dev"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: prism-dev
roleRef:
  kind: ClusterRole
  name: prism-dev-role
  apiGroup: rbac.authorization.k8s.io
