# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- define "spicedb.schema.zed" -}}

definition user {}

definition role {
    relation entity: platform | domain | cert | backend | computation
    relation member: user
    relation built_in_role: platform | domain | cert | backend | computation

    permission delete = entity->manage_role_permission - built_in_role->manage_role_permission
    permission update = entity->manage_role_permission - built_in_role->manage_role_permission
    permission read = entity->manage_role_permission - built_in_role->manage_role_permission

    permission add_user = entity->add_role_users_permission
    permission remove_user = entity->remove_role_users_permission
    permission view_user = entity->view_role_users_permission
}

definition cert {
    relation domain: domain
    relation platform: platform

    relation update: role#member
    relation read: role#member
    relation delete: role#member

    relation manage_role: role#member
    relation add_role_users: role#member
    relation remove_role_users: role#member
    relation view_role_users: role#member

    permission update_permission = update + domain->cert_update_permission + platform->admin
    permission read_permission = read + domain->cert_read_permission + platform->admin
    permission delete_permission = delete + domain->cert_delete_permission + platform->admin

    permission manage_role_permission = manage_role + domain->cert_manage_role_permission + platform->admin
    permission add_role_users_permission = add_role_users + domain->cert_add_role_users_permission + platform->admin
    permission remove_role_users_permission = remove_role_users + domain->cert_remove_role_users_permission + platform->admin
    permission view_role_users_permission = view_role_users + domain->cert_view_role_users_permission + platform->admin
}

definition backend {
    relation domain: domain
    relation platform: platform

    relation update: role#member
    relation read: role#member
    relation edit: role#member
    relation delete: role#member

    relation manage_role: role#member
    relation add_role_users: role#member
    relation remove_role_users: role#member
    relation view_role_users: role#member

    permission update_permission = update + domain->backend_update_permission + platform->admin
    permission read_permission = read + domain->backend_read_permission + platform->admin
    permission edit_permission = edit + domain->backend_edit_permission + platform->admin
    permission delete_permission = delete + domain->backend_delete_permission + platform->admin

    permission manage_role_permission = manage_role + domain->backend_manage_role_permission + platform->admin
    permission add_role_users_permission = add_role_users + domain->backend_add_role_users_permission + platform->admin
    permission remove_role_users_permission = remove_role_users + domain->backend_remove_role_users_permission + platform->admin
    permission view_role_users_permission = view_role_users + domain->backend_view_role_users_permission + platform->admin
}

definition computation {
    relation domain: domain
    relation platform: platform

    relation administrator: role#member
    relation edit: role#member
    relation run: role#member
    relation view: role#member

    relation dataset_provider: role#member
    relation algo_provider: role#member
    relation result_consumer: role#member

    permission edit_permission = edit + domain->computation_edit_permission + platform->admin
    permission run_permission = run + domain->computation_run_permission + platform->admin
    permission owner = administrator + platform->admin + domain->admin
    permission view_permission = view + domain->computation_read_permission + platform->admin

    permission dataset_provide_permission = dataset_provider + domain->computation_dataset_provide_permission + platform->admin
    permission algo_provide_permission = algo_provider + domain->computation_algo_provide_permission + platform->admin
    permission result_consume_permission = result_consumer + domain->computation_result_consume_permission + platform->admin
}

definition domain {
    relation platform: platform

    relation update: role#member
    relation read: role#member
    relation delete: role#member

    relation manage_role: role#member
    relation add_role_users: role#member
    relation remove_role_users: role#member
    relation view_role_users: role#member

    relation cert_update: role#member
    relation cert_read: role#member
    relation cert_delete: role#member

    relation backend_update: role#member
    relation backend_read: role#member
    relation backend_edit: role#member
    relation backend_delete: role#member

    relation computation_update: role#member
    relation computation_read: role#member
    relation computation_edit: role#member
    relation computation_run: role#member
    relation computation_delete: role#member
    relation computation_dataset_provide: role#member
    relation computation_algo_provide: role#member
    relation computation_result_consume: role#member

    permission update_permission = update + platform->admin
    permission read_permission = read + platform->admin
    permission delete_permission = delete + platform->admin
    permission membership = read + update + delete + platform->admin
    permission admin = read & update & delete & manage_role & add_role_users & remove_role_users & view_role_users

    permission manage_role_permission = manage_role + platform->admin
    permission add_role_users_permission = add_role_users + platform->admin
    permission remove_role_users_permission = remove_role_users + platform->admin
    permission view_role_users_permission = view_role_users + platform->admin

    permission cert_update_permission = cert_update + platform->admin
    permission cert_read_permission = cert_read + platform->admin
    permission cert_delete_permission = cert_delete + platform->admin

    permission backend_update_permission = backend_update + platform->admin
    permission backend_read_permission = backend_read + platform->admin
    permission backend_edit_permission = backend_edit + platform->admin
    permission backend_delete_permission = backend_delete + platform->admin

    permission computation_update_permission = computation_update + platform->admin
    permission computation_read_permission = computation_read + platform->admin
    permission computation_edit_permission = computation_edit + platform->admin
    permission computation_run_permission = computation_run + platform->admin
    permission computation_delete_permission = computation_delete + platform->admin
    permission computation_dataset_provide_permission = computation_dataset_provide + platform->admin
    permission computation_algo_provide_permission = computation_algo_provide + platform->admin
    permission computation_result_consume_permission = computation_result_consume + platform->admin
}

definition platform {
  relation administrator: user
  relation member: user

  permission admin = administrator
  permission membership = administrator + member
}

{{- end -}}
