# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-traefik
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
    component: traefik
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: "web"
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: "websecure"
    - name: tcp
      protocol: TCP
      port: 7018
      targetPort: "tcp"
    - name: traefik-dashboard
      protocol: TCP
      port: 8080
      targetPort: "traefik"
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: "prometheus"
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: "grafana"
    - name: argoui
      protocol: TCP
      port: 8085
      targetPort: "argoui"
    - name: argo-rollouts
      protocol: TCP
      port: 3100
      targetPort: "rollouts"
    - name: opensearch
      protocol: TCP
      port: 5601
      targetPort: "opensearch"
