# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-traefik
  namespace: prism-dev
spec:
  selector:
    app: prism-dev-traefik
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: 443
    - name: tcp
      protocol: TCP
      port: 7011
      targetPort: 7011
  type: LoadBalancer

