# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- define "traefik-dynamic-config.toml" -}}
# HTTP Routers
[http.routers.computations]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/computations`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/computations`) {{- end }}"
  entrypoints = ["websecure"]
  middlewares = ["headers-middleware", "retry-middleware"]
  service = "computations"
  priority = 1

[http.routers.computations-health]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/computations/health`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/computations/health`) {{- end }}"
  entrypoints = ["web"]
  middlewares = ["computations-stripprefix", "headers-middleware", "retry-middleware"]
  service = "computations"
  priority = 2

[http.routers.computation-policies]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/computations/policies`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/computations/policies`) {{- end }}"
  entrypoints = ["web"]
  middlewares = ["computations-stripprefix", "headers-middleware", "retry-middleware"]
  service = "computations"

[http.routers.users]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/users`)  ||  PathPrefix(`/password`)  {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/users`) ||  PathPrefix(`/password`) {{- end }}"
  entrypoints = ["websecure"]
  middlewares = ["headers-middleware", "retry-middleware"]
  service = "users"
  priority = 1

[http.routers.users-policies]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/policies`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/policies`) {{- end }}"
  entrypoints = ["web"]
  middlewares = ["headers-middleware", "retry-middleware"]
  service = "users"
  priority = 2

[http.routers.users-health]
  rule = "PathPrefix(`/users/health`)"
  entrypoints = ["web"]
  middlewares = ["users-stripprefix", "headers-middleware", "retry-middleware"]
  service = "users"
  priority = 3

[http.routers.health]
  rule = "PathPrefix(`/health`)"
  entrypoints = ["web"]
  service = "computations"

[http.routers.ui]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/ui`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/ui`) {{- end }}"
  entrypoints = ["websecure"]
  middlewares = ["headers-middleware", "retry-middleware"]
  service = "ui"
  priority = 1
  [http.routers.ui.tls]
    certResolver = "letsEncrypt"

[http.routers.dashboard]
  rule = "Path(`/`)"
  entrypoints = ["websecure"]
  middlewares = ["headers-middleware", "retry-middleware", "force-dashboard"]
  service = "ui"
  priority = 1

[http.routers.backends]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/backends`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/backends`) {{- end }}"
  entrypoints = ["websecure"]
  middlewares = ["headers-middleware", "retry-middleware"]
  service = "backends"
  priority = 1

[http.routers.certs]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/certs`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/certs`) {{- end }}"
  entrypoints = ["websecure"]
  middlewares = ["headers-middleware", "retry-middleware"]
  service = "certs"
  priority = 1

[http.routers.am-certs]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/am-certs`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/am-certs`) {{- end }}"
  entrypoints = ["websecure"]
  middlewares = ["headers-middleware", "retry-middleware"]
  service = "am-certs"
  priority = 1

[http.routers.workspaces]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/workspaces`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/workspaces`) {{- end }}"
  entrypoints = ["websecure"]
  middlewares = ["workspaces-stripprefix", "headers-middleware", "retry-middleware"]
  service = "workspaces"
  priority = 1

[http.routers.auth]
  rule = "{{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) && PathPrefix(`/auth`) {{- else }} Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/auth`) {{- end }}"
  entrypoints = ["websecure"]
  middlewares = ["auth-stripprefix", "headers-middleware", "retry-middleware"]
  service = "auth"
  priority = 1


# HTTP Services
[http.services.computations]
  [http.services.computations.loadBalancer]
    [[http.services.computations.loadBalancer.servers]]
      url = "http://{{ .Release.Name }}-computations:9000"
  [http.services.computations.loadBalancer.healthCheck]
    path = "/health"
    interval = "10s"
    timeout = "3s"

[http.services.users]
  [http.services.users.loadBalancer]
    [[http.services.users.loadBalancer.servers]]
      url = "http://{{ .Release.Name }}-users:9003"
  [http.services.users.loadBalancer.healthCheck]
    path = "/health"
    interval = "10s"
    timeout = "3s"

[http.services.ui]
  [http.services.ui.loadBalancer]
    [[http.services.ui.loadBalancer.servers]]
      url = "http://{{ .Release.Name }}-ui:9095"
  [http.services.ui.loadBalancer.healthCheck]
    path = "/health"
    interval = "10s"
    timeout = "3s"

[http.services.backends]
  [http.services.backends.loadBalancer]
    [[http.services.backends.loadBalancer.servers]]
      url = "http://{{ .Release.Name }}-backends:9011"
  [http.services.backends.loadBalancer.healthCheck]
    path = "/health"
    interval = "10s"
    timeout = "3s"

[http.services.certs]
  [http.services.certs.loadBalancer]
    [[http.services.certs.loadBalancer.servers]]
      url = "http://{{ .Release.Name }}-certs:8090"
  [http.services.certs.loadBalancer.healthCheck]
    path = "/health"
    interval = "10s"
    timeout = "3s"

[http.services.am-certs]
  [http.services.am-certs.loadBalancer]
    [[http.services.am-certs.loadBalancer.servers]]
      url = "http://{{ .Release.Name }}-am-certs:9010"
  [http.services.am-certs.loadBalancer.healthCheck]
    path = "/health"
    interval = "10s"
    timeout = "3s"

[http.services.auth]
  [http.services.auth.loadBalancer]
    [[http.services.auth.loadBalancer.servers]]
      url = "http://{{ .Release.Name }}-auth:8189"
  [http.services.auth.loadBalancer.healthCheck]
    path = "/health"
    interval = "10s"
    timeout = "3s"

[http.services.workspaces]
  [http.services.workspaces.loadBalancer]
    [[http.services.workspaces.loadBalancer.servers]]
      url = "http://{{ .Release.Name }}-domains:9013"
  [http.services.workspaces.loadBalancer.healthCheck]
    path = "/health"
    interval = "10s"
    timeout = "3s"

# HTTP Middlewares
[http.middlewares.computations-stripprefix]
  [http.middlewares.computations-stripprefix.stripPrefix]
    prefixes = ["/computations/"]

[http.middlewares.users-stripprefix]
  [http.middlewares.users-stripprefix.stripPrefix]
    prefixes = ["/users/"]

[http.middlewares.auth-stripprefix]
  [http.middlewares.auth-stripprefix.stripPrefix]
    prefixes = ["/auth/"]

[http.middlewares.am-certs-stripprefix]
  [http.middlewares.am-certs-stripprefix.stripPrefix]
    prefixes = ["/am-certs/"]

[http.middlewares.force-dashboard]
  [http.middlewares.force-dashboard.replacePath]
    path = "/ui"

[http.middlewares.workspaces-stripprefix]
  [http.middlewares.workspaces-stripprefix.stripPrefix]
    prefixes = ["/workspaces/"]

[http.middlewares.retry-middleware]
  [http.middlewares.retry-middleware.retry]
    attempts = 5
    initialInterval = "100ms"

[http.middlewares.headers-middleware]
  [http.middlewares.headers-middleware.headers]
    frameDeny = true
    browserXssFilter = true

[tcp]
  [tcp.routers]
    [tcp.routers.all-hosts-router]
      entryPoints = ["tcp"]
      rule = "HostSNI(`*`)"
      service = "backend-service"

  [tcp.services]
    [tcp.services.backend-service]
      [tcp.services.backend-service.loadBalancer]
        [[tcp.services.backend-service.loadBalancer.servers]]
          address = "backends:7018"

{{- end -}}
