# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-traefik-config
  namespace: prism-dev
data:
  traefik.toml: |
    [entryPoints]
      [entryPoints.web]
        address = ":80"
      [entryPoints.websecure]
        address = ":443"

    [certificatesResolvers.myresolver.acme]
      email = "info@ultraviolet.rs"
      storage = "/data/acme.json"
      httpChallenge = { entryPoint = "web" }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dynamic-config
  namespace: prism-dev
data:
  dynamic.toml: |
    http:
      routers:
        my-router:
          rule: "Host(`example.com`)"
          service: "my-service"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-traefik
  namespace: prism-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prism-dev-traefik
  template:
    metadata:
      labels:
        app: prism-dev-traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v3.1
        imagePullPolicy: IfNotPresent
        args:
          - "--api.dashboard=true"
          - "--providers.kubernetesingress=true"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
          - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
          - "--certificatesresolvers.myresolver.acme.email=info@ultraviolet.rs"
          - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
          - "--providers.file.filename=/etc/traefik/dynamic.toml" # Add this line to load the dynamic config
        ports:
          - name: web
            containerPort: 80
          - name: websecure
            containerPort: 443
        volumeMounts:
          - name: acme
            mountPath: /data
          - name: traefik-config
            mountPath: /etc/traefik/traefik.toml
            subPath: traefik.toml
          - name: dynamic-config
            mountPath: /etc/traefik/dynamic.toml
            subPath: dynamic.toml
      volumes:
        - name: acme
          persistentVolumeClaim:
            claimName: traefik-acme-new
        - name: traefik-config
          configMap:
            name: {{ .Release.Name }}-traefik-config
        - name: dynamic-config
          configMap:
            name: {{ .Release.Name }}-dynamic-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-acme-new
  namespace: prism-dev
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "prism-dev"
    meta.helm.sh/release-namespace: "prism-dev"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
