# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-traefik
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
    component: traefik
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: "web"
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: "websecure"
    - name: tcp
      protocol: TCP
      port: 7011
    - name: dashboard
      protocol: TCP
      port: 8080
      targetPort: "dashboard"
