# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: traefik
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.10.4
          imagePullPolicy: IfNotPresent
          args:
            - "--configFile=/etc/traefik/traefik.toml"
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            {{- if .Values.traefik.dashboard.enabled }}
            - name: dashboard
              containerPort: 8080
            {{- end }}
            - name: tcp
              containerPort: 7011

          volumeMounts:
            - name: {{ .Release.Name }}-traefik-cert
              mountPath: /etc/traefik/ssl/certs
            - name: {{ .Release.Name }}-traefik-config
              mountPath: /etc/traefik
            - name: {{ .Release.Name }}-dynamic-config
              mountPath: /etc/traefik/dynamic
      volumes:
        - name: {{ .Release.Name }}-traefik-config
          configMap:
            name: {{ .Release.Name }}-traefik-config
        - name: {{ .Release.Name }}-dynamic-config
          configMap:
            name: {{ .Release.Name }}-dynamic-config
        - name: {{ .Release.Name }}-traefik-cert
          configMap:
            name: {{ .Release.Name }}-traefik-acme-cert-config
