# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-traefik
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
    component: traefik
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: "web"
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: "websecure"
    - name: tcp
      protocol: TCP
      port: 7011
    - name: traefik-dashboard
      protocol: TCP
      port: 8080
      targetPort: "traefik"
    - name: k8s-dashboard
      protocol: TCP
      port: 9200
      targetPort: "k8s"
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: "prometheus"
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: "grafana"
