# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- define "traefik-static-config.toml" -}}
[log]
  level = "INFO"
  filePath = "/var/log/traefik/traefik.log"
  format = "json"

[accessLog]
  filePath = "/var/log/traefik/access.log"
  bufferingSize = 1000
  format = "json"

[api]
  dashboard = true
  # Set to true for dev.
  insecure = true

[providers.file]
  filename = "/etc/traefik/dynamic/dynamic.toml"
  watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "letsEncrypt"

  [entryPoints.tcp]
    address = ":7011"

  [entryPoints.traefik]
    address = ":8080"

  [entryPoints.k8s]
    address = ":9200"

  [entryPoints.prometheus]
    address = ":9090"

  [entryPoints.grafana]
    address = ":3000"

  [entryPoints.argoui]
    address = ":8085"

  [entryPoints.rollouts]
    address = ":3100"


[providers]
  [providers.kubernetesCRD]
    namespaces = ["{{ .Release.Namespace }}", "argocd"]
    allowEmptyServices = true
    allowCrossNamespace = true
  [providers.kubernetesIngress]
    allowEmptyServices = true

[certificatesResolvers.letsEncrypt.acme]
  email = "info@ultraviolet.com"
  storage = "/data/acme.json"
  [certificatesResolvers.letsEncrypt.acme.httpChallenge]
    entryPoint = "web"

[tracing]
  [tracing.jaeger]
    samplingType = "const"
    samplingParam = 1
    gen128Bit = true
    [tracing.jaeger.collector]
      endpoint = "http://{{ .Values.jaeger.fullnameOverride }}-collector:14268/api/traces"
{{- end -}}
