# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: {{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) {{ else }} Host(`staging.prism.ultraviolet.rs`) {{- end }}
      kind: Rule
      middlewares:
        - name: {{ .Release.Name }}-middleware
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ .Release.Name }}-ui
          namespace: {{ .Release.Namespace }}
          port: 9095
  tls:
    certResolver: letsEncrypt


{{- if .Values.traefik.dashboard.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-traefik-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - traefik
  routes:
    - match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService

{{- end }}


{{- if .Values.argocd.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-argo-ui
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: >-
        {{- if .Values.env.prod }}
        Host(`prism.ultraviolet.rs`) && PathPrefix(`/argocd`)
        {{- else }}
        Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/argocd`)
        {{- end }}
      priority: 10
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
          scheme: http
  tls:
    certResolver: letsEncrypt
{{- end }}


{{- if .Values.argoRollouts.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-argo-rollouts-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: >-
        {{- if .Values.env.prod }}
        Host(`prism.ultraviolet.rs`) && PathPrefix(`/rollouts`)
        {{- else }}
        Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/rollouts`)
        {{- end }}
      priority: 10
      services:
        - name: argo-rollouts-dashboard
          namespace: {{ .Release.Namespace }}
          port: 3100
  tls:
    certResolver: letsEncrypt

{{- end }}

{{- if .Values.opensearch.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-opensearch-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /opensearch
    forceSlash: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-open-search-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: >-
        {{- if .Values.env.prod }}
        Host(`prism.ultraviolet.rs`) && PathPrefix(`/opensearch`)
        {{- else }}
        Host(`staging.prism.ultraviolet.rs`) && PathPrefix(`/opensearch`)
        {{- end }}
      priority: 10
      middlewares:
        - name: {{ .Release.Name }}-opensearch-strip-prefix
          namespace: {{ .Release.Namespace }}
      services:
        - name: prism-opensearch-dashboards
          namespace: {{ .Release.Namespace }}
          port: 5601
          kind: Service
{{- end }}


{{- if .Values.prometheus.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-prometheus-grafana
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) {{ else }} Host(`staging.prism.ultraviolet.rs`) {{- end }} && PathPrefix(`/grafana`)
      kind: Rule
      middlewares:
        - name: {{ .Release.Name }}-garafana-strip-prefix
          namespace: {{ .Release.Namespace }}
      services:
        - name: prism-staging-grafana
          namespace: {{ .Release.Namespace }}
          port: 80
          kind: Service
  tls:
    certResolver: letsEncrypt
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-garafana-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /grafana
    forceSlash: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{- if .Values.env.prod }} Host(`prism.ultraviolet.rs`) {{ else }} Host(`staging.prism.ultraviolet.rs`) {{- end }} && PathPrefix(`/prometheus`)
      kind: Rule
      middlewares:
        - name: {{ .Release.Name }}-prometheus-strip-prefix
          namespace: {{ .Release.Namespace }}
      services:
        - name: prism-monitoring-stack-prometheus
          namespace: {{ .Release.Namespace }}
          port: 9090
          kind: Service
  tls:
    certResolver: letsEncrypt

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-prometheus-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /prometheus
    forceSlash: true

{{- end }}
