# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: traefik
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: false
      containers:
        - name: traefik
          image: traefik:v2.10.4
          imagePullPolicy: Always
          args:
            - "--configFile=/etc/traefik/traefik.toml"
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
            - name: websecure
              containerPort: 443
              protocol: TCP
            {{- if .Values.traefik.dashboard.enabled }}
            - name: traefik
              containerPort: 8080
              protocol: TCP
            {{- end }}
            - name: tcp
              containerPort: 7011
              protocol: TCP
            {{- if .Values.k8sdashboard.enabled }}
            - name: k8s
              containerPort: 9200
              protocol: TCP
            {{- end }}

            {{- if .Values.prometheus.enabled }}
            - name: prometheus
              containerPort: 9090
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
            {{- end }}

          volumeMounts:
            - name: {{ .Release.Name }}-traefik-config
              mountPath: /etc/traefik
            - name: {{ .Release.Name }}-dynamic-config
              mountPath: /etc/traefik/dynamic
            - name: {{ .Release.Name }}-acme
              mountPath: /data
            - name: logs
              mountPath: /var/log/traefik
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: logs
          emptyDir: { }
        - name: {{ .Release.Name }}-traefik-config
          configMap:
            name: {{ .Release.Name }}-traefik-config
        - name: {{ .Release.Name }}-dynamic-config
          configMap:
            name: {{ .Release.Name }}-dynamic-config
        - name: {{ .Release.Name }}-acme
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-traefik-acme-pvc