# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-traefik
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: traefik
    release: {{ .Values.prometheus.fullnameOverride }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: traefik
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
    honorTimestamps: true
{{- end }}