# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ui-env-vars
data:
  PRISM_UI_LOG_LEVEL: {{ default .Values.defaults.logLevel .Values.ui.logLevel | quote }}
  PRISM_UI_HTTP_PORT: {{ .Values.ui.httpPort | quote }}
  PRISM_UI_INSTANCE_ID: {{ .Values.ui.instanceId | quote }}
  PRISM_UI_PATH_PREFIX: {{ .Values.ui.pathPrefix | quote }}
  PRISM_UI_COMPUTATIONS_PATH_PREFIX: {{ .Values.ui.computationsPathPrefix | quote }}
  PRISM_UI_DOMAINS_HOST: "{{ .Release.Name }}-{{ .Values.auth.host }}"
  PRISM_UI_DOMAINS_PORT: {{ .Values.auth.httpPort | quote }}
  PRISM_UI_BILLING_URL: "http://{{ .Release.Name }}-{{ .Values.billing.host }}:{{ .Values.billing.httpPort }}"
  PRISM_UI_USERS_URL: "http://{{ .Release.Name }}-{{ .Values.users.host }}:{{ .Values.users.httpPort }}"
  PRISM_UI_COMPUTATIONS_URL: "http://{{ .Release.Name }}-{{ .Values.computations.host }}:{{ .Values.computations.httpPort }}"
  PRISM_UI_RETURN_URL: {{ .Values.ui.returnUrl | quote }}
  PRISM_AUTH_GRPC_URL: "{{ .Release.Name }}-{{ .Values.auth.host }}:{{ .Values.auth.grpcPort }}"
  PRISM_CERTS_UI_URL: "https://prism.ultraviolet.rs/certs"
  PRISM_CLIENTS_URL: "http://{{ .Release.Name }}-{{ .Values.users.host }}:{{ .Values.users.httpPort }}"
  PRISM_EMAIL_FROM_ADDRESS: "adminemail@gmail.com"
  PRISM_EMAIL_FROM_NAME: "PRISM"
  PRISM_EMAIL_HOST: "smtp.gmail.com"
  PRISM_EMAIL_PORT: "587"
  PRISM_EMAIL_TEMPLATE: "/templates/reset.tmpl"
  PRISM_SPICEDB_HOST: "{{ .Release.Name }}-{{ .Values.spicedb.host }}"
  PRISM_SPICEDB_PORT: {{ .Values.spicedb.grpc.port | quote }}
  PRISM_UI_BACKENDS_URL: "http://{{ .Release.Name }}-{{ .Values.backends.host }}:{{ .Values.backends.httpPort }}"
  PRISM_UI_BILLING_PERMISSIONS_URL: "http://{{ .Release.Name }}-{{ .Values.billingPermissions.host }}:{{ .Values.billingPermissions.httpPort }}"
  PRISM_UI_CERTS_URL: "http://{{ .Release.Name }}-{{ .Values.certs.host }}:{{ .Values.certs.httpPort }}"
  PRISM_UI_DOMAINS_HTTP_URL: "http://{{ .Release.Name }}-{{ .Values.domains.host }}:{{ .Values.domains.httpPort }}"
  PRISM_UI_DOMAINS_URL: "http://{{ .Release.Name }}-{{ .Values.domains.host }}:{{ .Values.domains.httpPort }}"
  PRISM_UI_PORT: {{ .Values.ui.httpPort | quote }}
  PRISM_VERIFICATION_TLS: "false"
  PRISM_AUTH_GRPC_CLIENT_CERT: ""
  PRISM_AUTH_GRPC_CLIENT_KEY: ""
  PRISM_AUTH_GRPC_SERVER_CA_CERTS: ""
  PRISM_BILLING: {{ .Values.billing.enabled | quote}}
  PRISM_UI_HOST: "0.0.0.0"
  PRISM_DOMAINS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.domains.host }}:{{ .Values.domains.grpcPort }}"
  PRISM_DOMAINS_GRPC_TIMEOUT: "10s"
  PRISM_DOMAINS_GRPC_CLIENT_CERT: ""
  PRISM_DOMAINS_GRPC_CLIENT_KEY: ""
  PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS: ""
  PRISM_JAEGER_URL: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.defaults.jaegerCollectorPort }}/v1/traces"
  PRISM_JAEGER_TRACE_RATIO: {{ default .Values.defaults.jaegerTraceRatio .Values.defaults.jaegerTraceRatio | quote }}

