# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: ui
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.ui.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: ui
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.ui.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-ui
          image: "{{ default (printf "%s/ui" .Values.defaults.image.rootRepository) .Values.ui.image.repository }}:{{ default .Values.defaults.image.tag .Values.ui.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.ui.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-ui-env-vars
          ports:
            - containerPort: {{ .Values.ui.httpPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-ui-ssl-config
              mountPath: /ssl/certs/ui
              readOnly: true
            - mountPath: /templates
              name: {{ .Release.Name }}-user-email-config
      volumes:
        - name: {{ .Release.Name }}-ui-ssl-config
          configMap:
            name: {{ .Release.Name }}-ui-ssl-files
        - name: {{ .Release.Name }}-user-email-config
          configMap:
            name: {{ .Release.Name }}-user-email-template-config

      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
