# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
        - setWeight: 100
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable: 0%
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: ui
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.ui.httpPort }}"
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "{{ if .Values.env.prod }}https{{ else }}http{{ end }}"
        checksum/config: {{ include (print $.Template.BasePath "/ui-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        component: ui
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.ui.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-ui
          image: "{{ default (printf "%s/ui" .Values.defaults.image.rootRepository) .Values.ui.image.repository }}:{{ default .Values.defaults.image.tag .Values.ui.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.ui.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-ui-env-vars
          env:
            - name: PRISM_UI_STRIPE_PK
              valueFrom:
                secretKeyRef:
                  name: prism-ui-secrets
                  key: PRISM_UI_STRIPE_PK
            - name: PRISM_UI_HASH_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-ui-secrets
                  key: PRISM_UI_HASH_KEY
            - name: PRISM_UI_BLOCK_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-ui-secrets
                  key: PRISM_UI_BLOCK_KEY
            - name: PRISM_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prism-ui-secrets
                  key: PRISM_EMAIL_PASSWORD
            - name: PRISM_EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: prism-ui-secrets
                  key: PRISM_EMAIL_USERNAME
            - name: PRISM_STRIPE_PK
              valueFrom:
                secretKeyRef:
                  name: prism-ui-secrets
                  key: PRISM_STRIPE_PK
            - name: PRISM_SPICEDB_PRE_SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-spicedb-secrets
                  key: PRISM_SPICEDB_PRE_SHARED_KEY
            - name: PRISM_AUTH_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_CERT
            - name: PRISM_AUTH_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_KEY
            - name: PRISM_AUTH_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_AUTH_GRPC_SERVER_CA_CERTS
            - name: PRISM_DOMAINS_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_CERT
            - name: PRISM_DOMAINS_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_KEY
            - name: PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_CA_CERTS
            - name: PRISM_PADDLE_CLIENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: prism-paddle-secrets
                  key: PRISM_PADDLE_CLIENT_TOKEN

            - name: PRISM_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: prism-google-cloud-oauth-secrets
                  key: PRISM_GOOGLE_CLIENT_ID

            - name: PRISM_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: prism-google-cloud-oauth-secrets
                  key: PRISM_GOOGLE_CLIENT_SECRET

            - name: PRISM_GOOGLE_STATE
              valueFrom:
                secretKeyRef:
                  name: prism-google-cloud-oauth-secrets
                  key: PRISM_GOOGLE_STATE
          ports:
            - containerPort: {{ .Values.ui.httpPort }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ 'ALL' ]
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ui.httpPort }}
              scheme: {{ if .Values.env.prod }}HTTPS{{ else }}HTTP{{ end }}
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ui.httpPort }}
              scheme: {{ if .Values.env.prod }}HTTPS{{ else }}HTTP{{ end }}
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /templates
              name: {{ .Release.Name }}-user-email-config
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: {{ .Release.Name }}-user-email-config
          configMap:
            name: {{ .Release.Name }}-user-email-template-config