# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: ui
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.ui.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: ui
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.ui.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-ui
          image: "{{ default (printf "%s/ui" .Values.defaults.image.rootRepository) .Values.ui.image.repository }}:{{ default .Values.defaults.image.tag .Values.ui.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.ui.image.pullPolicy }}
          env:
            - name: PRISM_UI_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.ui.logLevel | quote }}
            - name: PRISM_UI_HTTP_PORT
              value: {{ .Values.ui.httpPort | quote }}
            - name: PRISM_UI_INSTANCE_ID
              value: {{ .Values.ui.instanceId | quote }}
            - name: PRISM_UI_PATH_PREFIX
              value: {{ .Values.ui.pathPrefix | quote }}
            - name: PRISM_UI_COMPUTATIONS_PATH_PREFIX
              value: {{ .Values.ui.computationsPathPrefix | quote }}
            - name: PRISM_UI_DOMAINS_HOST
              value: {{ .Values.ui.domainsHost | quote }}
            - name: PRISM_UI_DOMAINS_PORT
              value: {{ .Values.ui.domainsPort | quote }}
            - name: PRISM_UI_BILLING_URL
              value: {{ .Values.ui.billingUrl | quote }}
            - name: PRISM_UI_INVITATIONS_URL
              value: {{ .Values.ui.invitationsUrl | quote }}
            - name: PRISM_UI_USERS_URL
              value: {{ .Values.ui.usersUrl | quote }}
            - name: PRISM_UI_COMPUTATIONS_URL
              value: {{ .Values.ui.computationsUrl | quote }}
            - name: PRISM_UI_STRIPE_PK
              value: {{ .Values.ui.stripePk | quote }}
            - name: PRISM_UI_RETURN_URL
              value: {{ .Values.ui.returnUrl | quote }}
            - name: PRISM_UI_HASH_KEY
              value: {{ .Values.ui.hashKey | quote }}
            - name: PRISM_UI_BLOCK_KEY
              value: {{ .Values.ui.blockKey | quote }}
          ports:
            - containerPort: {{ .Values.ui.httpPort }}
              protocol: TCP
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
