# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  selector:
    app: {{ .Release.Name }}
    component: ui
  ports:
    - port: {{ .Values.ui.httpPort }}
      protocol: TCP
