# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.service.name | default "ui-service" }}  # Service name from values.yaml
  labels:
    app: {{ .Values.ui.appLabel | default "ui" }}
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}  # Service type from values.yaml
  ports:
    - port: {{ .Values.ui.service.port | default 80 }}  # External port
      targetPort: {{ .Values.ui.port | default 9095 }}  # Internal container port
  selector:
    app: {{ .Values.ui.appLabel | default "ui" }}
