# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-users-env-vars
  namespace: {{ .Release.Namespace }}
data:
  SMQ_JAEGER_URL: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.jaeger.collector.service.otlp.http.port }}/v1/traces"
  SMQ_JAEGER_TRACE_RATIO: {{ default .Values.defaults.jaegerTraceRatio .Values.users.jaegerTraceRatio | quote }}
  SMQ_SEND_TELEMETRY: {{ default .Values.defaults.sendTelemetry .Values.users.sendTelemetry | quote }}
  SMQ_ES_URL: "{{ .Release.Name}}-{{ .Values.defaults.eventStreamURL }}"
  SMQ_USERS_LOG_LEVEL: {{ default .Values.defaults.logLevel .Values.users.logLevel | quote }}
  SMQ_USERS_HTTP_HOST: "0.0.0.0"
  SMQ_USERS_HTTP_PORT: {{ .Values.users.httpPort | quote }}
  SMQ_TOKEN_RESET_ENDPOINT: {{ .Values.users.tokenResetEndpoint | quote }}
  SMQ_USERS_PASS_REGEX: {{ .Values.users.passwordRegex | quote }}
  SMQ_USERS_ALLOW_SELF_REGISTER: {{ .Values.users.allowSelfRegister | quote }}
  SMQ_USERS_DELETE_INTERVAL: {{ .Values.users.deleteInterval | quote }}
  SMQ_USERS_DELETE_AFTER: {{ .Values.users.deleteAfter | quote }}
  SMQ_USERS_DB_HOST:
    {{- if .Values.postgresqlusers.enabled }}
      "{{ .Release.Name }}-postgresqlusers"
    {{- else }}
      {{ .Values.postgresqlusers.host | quote }}
    {{- end }}
  SMQ_USERS_DB_PORT: {{ .Values.postgresqlusers.port | quote }}
  SMQ_USERS_DB_NAME: {{ .Values.postgresqlusers.database | quote }}
  SMQ_USERS_DB_USER: {{ .Values.postgresqlusers.username | quote }}
  SMQ_USERS_GRPC_HOST: "0.0.0.0"
  SMQ_USERS_GRPC_PORT: {{ .Values.users.mgGrpcPort | quote }}
  PRISM_SPICEDB_HOST: "{{ .Release.Name }}-{{ .Values.spicedb.host }}"
  PRISM_SPICEDB_PORT: {{ .Values.spicedb.grpc.port | quote }}
  SMQ_AUTH_GRPC_URL: "{{ .Release.Name }}-{{ .Values.auth.host }}:{{ .Values.auth.grpcPort }}"
  SMQ_AUTH_GRPC_TIMEOUT: "10s"
  SMQ_EMAIL_FROM_NAME: "PRISM"
  SMQ_EMAIL_HOST: "smtp.gmail.com"
  SMQ_EMAIL_PORT: "587"
  SMQ_EMAIL_TEMPLATE: "/templates/invite.tmpl"
  SMQ_USERS_ACCESS_TOKEN_DURATION: "30m"
  SMQ_USERS_DB: {{ .Values.postgresqlusers.database | quote }}
  SMQ_USERS_DB_SSL_CERT: ""
  SMQ_USERS_DB_SSL_KEY: ""
  SMQ_USERS_DB_SSL_MODE: "disable"
  SMQ_USERS_DB_SSL_ROOT_CERT: ""
  SMQ_USERS_REFRESH_TOKEN_DURATION: "24h"
  SMQ_USERS_RESET_PWD_TEMPLATE: "/templates/reset.tmpl"
  SMQ_SPICEDB_HOST: "{{ .Release.Name }}-{{ .Values.spicedb.host }}"
  SMQ_SPICEDB_PORT: {{ .Values.spicedb.grpc.port | quote }}
  SMQ_DOMAINS_GRPC_URL: "{{ .Release.Name }}-{{ .Values.domains.host }}:{{ .Values.domains.grpcPort }}"
  SMQ_DOMAINS_GRPC_TIMEOUT: "10s"
  SMQ_GOOGLE_REDIRECT_URL: "{{ .Values.env.prod | ternary "prism.ultraviolet.rs" "staging.prism.ultraviolet.rs" }}/oauth/callback/google"
  SMQ_OAUTH_UI_REDIRECT_URL: "{{ .Values.env.prod | ternary "prism.ultraviolet.rs" "staging.prism.ultraviolet.rs" }}/ui/tokens/secure"
  SMQ_OAUTH_UI_ERROR_URL: "{{ .Values.env.prod | ternary "prism.ultraviolet.rs" "staging.prism.ultraviolet.rs" }}/ui/login"

