# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-users
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
    component: users
  ports:
    - protocol: TCP
      port: {{ .Values.users.httpPort }}
      name: {{ .Release.Name }}-users-http
