# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-users
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    {{- if .Values.env.prod }}
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 80
        - pause: { duration: 2m }
        - setWeight: 100
    {{ else }}
    canary:
      maxSurge: 25%
      maxUnavailable: 0%
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: users
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.users.httpPort }}"
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "{{ if .Values.env.prod }}https{{ else }}http{{ end }}"
        checksum/config: {{ include (print $.Template.BasePath "/users-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        component: users
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.users.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-users
          image: "{{ default (printf "%s/users" .Values.defaults.image.rootRepository) .Values.users.image.repository }}:{{ default .Values.defaults.image.tag .Values.users.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.users.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-users-env-vars
          env:
            - name: SMQ_USERS_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: prism-users-secrets
                  key: SMQ_USERS_ADMIN_EMAIL
            - name: SMQ_USERS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prism-users-secrets
                  key: SMQ_USERS_ADMIN_PASSWORD
            - name: SMQ_USERS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-users-secrets
                  key: SMQ_USERS_SECRET_KEY
            - name: SMQ_USERS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prism-users-secrets
                  key: SMQ_USERS_DB_PASS
            - name: SMQ_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prism-users-secrets
                  key: SMQ_EMAIL_PASSWORD
            - name: SMQ_EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: prism-users-secrets
                  key: SMQ_EMAIL_USERNAME
            - name: SMQ_EMAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: prism-users-secrets
                  key: SMQ_EMAIL_FROM_ADDRESS
            - name: SMQ_SPICEDB_PRE_SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-spicedb-secrets
                  key: PRISM_SPICEDB_PRE_SHARED_KEY
            - name: SMQ_AUTH_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_CERT
            - name: SMQ_AUTH_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_AUTH_GRPC_CLIENT_KEY
            - name: SMQ_AUTH_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_AUTH_GRPC_SERVER_CA_CERTS
            - name: SMQ_USERS_GRPC_CLIENT_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_USERS_GRPC_CLIENT_CA_CERTS
            - name: SMQ_USERS_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_USERS_GRPC_SERVER_CA_CERTS
            - name: SMQ_USERS_GRPC_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_USERS_GRPC_SERVER_CERT
            - name: SMQ_USERS_GRPC_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_USERS_GRPC_SERVER_KEY
            - name: SMQ_USERS_HTTP_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_USERS_HTTP_SERVER_CERT
            - name: SMQ_USERS_HTTP_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_USERS_HTTP_SERVER_KEY
            - name: SMQ_DOMAINS_GRPC_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_KEY
            - name: SMQ_DOMAINS_GRPC_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-client-certs
                  key: PRISM_DOMAINS_GRPC_CLIENT_CERT
            - name: SMQ_DOMAINS_GRPC_SERVER_CA_CERTS
              valueFrom:
                secretKeyRef:
                  name: prism-shared-grpc-server-certs
                  key: PRISM_DOMAINS_GRPC_SERVER_CA_CERTS

            - name: SMQ_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: prism-google-cloud-oauth-secrets
                  key: PRISM_GOOGLE_CLIENT_ID

            - name: SMQ_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: prism-google-cloud-oauth-secrets
                  key: PRISM_GOOGLE_CLIENT_SECRET

            - name: SMQ_GOOGLE_STATE
              valueFrom:
                secretKeyRef:
                  name: prism-google-cloud-oauth-secrets
                  key: PRISM_GOOGLE_STATE
          ports:
            - containerPort: {{ .Values.users.httpPort }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ 'ALL' ]
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.users.httpPort }}
              scheme: {{ if .Values.env.prod }}HTTPS{{ else }}HTTP{{ end }}
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.users.httpPort }}
              scheme: {{ if .Values.env.prod }}HTTPS{{ else }}HTTP{{ end }}
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /templates
              name: {{ .Release.Name }}-user-email-config
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: {{ .Release.Name }}-user-email-config
          configMap:
            name: {{ .Release.Name }}-user-email-template-config
      {{- with .Values.users.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.users.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.users.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
