# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-backends
  namespace: {{ $.Release.Namespace }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ $.Release.Name }}-backends
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Release.Name }}-backends
        minAllowed:
          cpu: "250m"
          memory: "128Mi"
        maxAllowed:
          cpu: "1"
          memory: "1Gi"
        controlledResources: [ "cpu", "memory" ]