# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prism-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      spicedb=authzed/spicedb:latest,
      auth=ghcr.io/ultravioletrs/prism/auth:latest,
      ui=ghcr.io/ultravioletrs/prism/ui:latest,
      certs=ghcr.io/ultravioletrs/prism/certs:latest,
      backends=ghcr.io/ultravioletrs/prism/backends:latest,
      computations=ghcr.io/ultravioletrs/prism/computations:latest,
      users=supermq/users:latest,
      billing=ghcr.io/absmach/amdm/billing:prism-latest,
      amcerts=ghcr.io/absmach/certs:latest,
      domains=supermq/domains:latest,
      cvmbilling=ghcr.io/ultravioletrs/prism/cvm-billing:latest

    argocd-image-updater.argoproj.io/spicedb.update-strategy: digest
    argocd-image-updater.argoproj.io/spicedb.force-update: "true"

    argocd-image-updater.argoproj.io/auth.update-strategy: digest
    argocd-image-updater.argoproj.io/auth.force-update: "true"

    argocd-image-updater.argoproj.io/ui.update-strategy: digest
    argocd-image-updater.argoproj.io/ui.force-update: "true"

    argocd-image-updater.argoproj.io/certs.update-strategy: digest
    argocd-image-updater.argoproj.io/certs.force-update: "true"

    argocd-image-updater.argoproj.io/backends.update-strategy: digest
    argocd-image-updater.argoproj.io/backends.force-update: "true"

    argocd-image-updater.argoproj.io/computations.update-strategy: digest
    argocd-image-updater.argoproj.io/computations.force-update: "true"

    argocd-image-updater.argoproj.io/users.update-strategy: digest
    argocd-image-updater.argoproj.io/users.force-update: "true"

    argocd-image-updater.argoproj.io/billing.update-strategy: digest
    argocd-image-updater.argoproj.io/billing.force-update: "true"

    argocd-image-updater.argoproj.io/amcerts.update-strategy: digest
    argocd-image-updater.argoproj.io/amcerts.force-update: "true"

    argocd-image-updater.argoproj.io/domains.update-strategy: digest
    argocd-image-updater.argoproj.io/domains.force-update: "true"

    argocd-image-updater.argoproj.io/cvmbilling.update-strategy: digest
    argocd-image-updater.argoproj.io/cvmbilling.force-update: "true"

spec:
  ignoreDifferences:
    - group: ""
      kind: Secret
      namespace: staging
      jsonPointers:
        - /data
        - /stringData
  project: default
  source:
    repoURL: https://github.com/ultravioletrs/prism-helm.git
    targetRevision: main
    path: charts/prism
    helm:
      valueFiles:
        - environments/values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
