# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prism-production
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      auth=ghcr.io/ultravioletrs/prism/auth,
      ui=ghcr.io/ultravioletrs/prism/ui,
      certs=ghcr.io/ultravioletrs/prism/certs,
      backends=ghcr.io/ultravioletrs/prism/backends,
      computations=ghcr.io/ultravioletrs/prism/computations,
      users=supermq/users,
      billing=ghcr.io/absmach/amdm/billing,
      amCerts=ghcr.io/absmach/certs,
      domains=supermq/domains,
      cvmbilling=ghcr.io/ultravioletrs/prism/cvm-billing

    argocd-image-updater.argoproj.io/auth.update-strategy: newest-build
    argocd-image-updater.argoproj.io/auth.force-update: "true"
    argocd-image-updater.argoproj.io/auth.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/auth.helm.image-name: auth.image.repository
    argocd-image-updater.argoproj.io/auth.helm.image-tag: auth.image.tag
    argocd-image-updater.argoproj.io/auth.allow-tags: regexp:^v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/ui.update-strategy: newest-build
    argocd-image-updater.argoproj.io/ui.force-update: "true"
    argocd-image-updater.argoproj.io/ui.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/ui.helm.image-name: ui.image.repository
    argocd-image-updater.argoproj.io/ui.helm.image-tag: ui.image.tag
    argocd-image-updater.argoproj.io/ui.allow-tags: regexp:^v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/certs.update-strategy: newest-build
    argocd-image-updater.argoproj.io/certs.force-update: "true"
    argocd-image-updater.argoproj.io/certs.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/certs.helm.image-name: certs.image.repository
    argocd-image-updater.argoproj.io/certs.helm.image-tag: certs.image.tag
    argocd-image-updater.argoproj.io/certs.allow-tags: regexp:^v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/backends.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backends.force-update: "true"
    argocd-image-updater.argoproj.io/backends.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/backends.helm.image-name: backends.image.repository
    argocd-image-updater.argoproj.io/backends.helm.image-tag: backends.image.tag
    argocd-image-updater.argoproj.io/backends.allow-tags: regexp:^v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/computations.update-strategy: newest-build
    argocd-image-updater.argoproj.io/computations.force-update: "true"
    argocd-image-updater.argoproj.io/computations.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/computations.helm.image-name: computations.image.repository
    argocd-image-updater.argoproj.io/computations.helm.image-tag: computations.image.tag
    argocd-image-updater.argoproj.io/computations.allow-tags: regexp:^v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/users.update-strategy: newest-build
    argocd-image-updater.argoproj.io/users.force-update: "true"
    argocd-image-updater.argoproj.io/users.pull-secret: pullsecret:argocd/docker-secret
    argocd-image-updater.argoproj.io/users.helm.image-name: users.image.repository
    argocd-image-updater.argoproj.io/users.helm.image-tag: users.image.tag
    argocd-image-updater.argoproj.io/users.allow-tags: regexp:^v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/billing.update-strategy: newest-build
    argocd-image-updater.argoproj.io/billing.force-update: "true"
    argocd-image-updater.argoproj.io/billing.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/billing.helm.image-name: billing.image.repository
    argocd-image-updater.argoproj.io/billing.helm.image-tag: billing.image.tag
    argocd-image-updater.argoproj.io/billing.allow-tags: regexp:^prism-v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/amCerts.update-strategy: newest-build
    argocd-image-updater.argoproj.io/amCerts.force-update: "true"
    argocd-image-updater.argoproj.io/amCerts.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/amCerts.helm.image-name: amCerts.image.repository
    argocd-image-updater.argoproj.io/amCerts.helm.image-tag: amCerts.image.tag
    argocd-image-updater.argoproj.io/amCerts.allow-tags: regexp:^v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/domains.update-strategy: newest-build
    argocd-image-updater.argoproj.io/domains.force-update: "true"
    argocd-image-updater.argoproj.io/domains.pull-secret: pullsecret:argocd/docker-secret
    argocd-image-updater.argoproj.io/domains.helm.image-name: domains.image.repository
    argocd-image-updater.argoproj.io/domains.helm.image-tag: domains.image.tag
    argocd-image-updater.argoproj.io/domains.allow-tags: regexp:^v\d+\.\d+\.\d+$

    argocd-image-updater.argoproj.io/cvmbilling.update-strategy: newest-build
    argocd-image-updater.argoproj.io/cvmbilling.force-update: "true"
    argocd-image-updater.argoproj.io/cvmbilling.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/cvmbilling.helm.image-name: cvmbilling.image.repository
    argocd-image-updater.argoproj.io/cvmbilling.helm.image-tag: cvmbilling.image.tag
    argocd-image-updater.argoproj.io/cvmbilling.allow-tags: regexp:^v\d+\.\d+\.\d+$

spec:
  ignoreDifferences:
    - group: ""
      kind: Secret
      namespace: production
      jsonPointers:
        - /data
        - /stringData
  project: default
  source:
    repoURL: https://github.com/ultravioletrs/prism-helm.git
    targetRevision: production
    path: charts/prism
    helm:
      valueFiles:
        - environments/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
