name: Release Charts

on:
  push:
    branches:
      - main
    tags:
      - "prism-*"

jobs:
  release:
    permissions:
      pages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add Dependencies
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
          helm repo add hashicorp https://helm.releases.hashicorp.com
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
          helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Update Helm dependencies
        run: |
          helm dependency update charts/prism

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
